// Package migrations_test checks the conventions of the wrench migration files in this
// directory (the files themselves are SQL; see CLAUDE.md, "Schema migrations").
package migrations_test

import (
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// fileName is stricter than wrench's own pattern: six digits, a lowercase slug, no ".up".
var fileName = regexp.MustCompile(`^([0-9]{6})_[a-z0-9_]+\.sql$`)

const generatedHeader = "-- Code generated by scripts/db-schema.sh from db/migrations; DO NOT EDIT.\n"

func TestFilesAreNumberedSequentially(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatal(err)
	}
	var versions []int
	for _, e := range entries {
		name := e.Name()
		if strings.HasSuffix(name, ".go") {
			continue
		}
		m := fileName.FindStringSubmatch(name)
		if m == nil {
			t.Errorf("%s: migration files are NNNNNN_<lowercase_slug>.sql (task db:new NAME=<slug>)", name)
			continue
		}
		v, _ := strconv.Atoi(m[1])
		versions = append(versions, v)
	}
	// os.ReadDir sorts by name, and the zero padding makes that numeric order.
	for i, v := range versions {
		if v != i+1 {
			t.Fatalf("migration versions are %v; want 1..%d with no gaps or duplicates", versions, len(versions))
		}
	}
	if len(versions) == 0 {
		t.Fatal("no migration files; 000001_baseline.sql should be here")
	}
}

func TestSchemaSnapshotIsGenerated(t *testing.T) {
	data, err := os.ReadFile("../schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), generatedHeader) {
		t.Errorf("db/schema.sql must start with %q: add a migration and run task db:schema"+
			" instead of editing it", generatedHeader)
	}
}
