// Code generated by weaver from obs/semconv/registry; DO NOT EDIT.
//
// The names of Just a Bill's own telemetry: every justabill.* attribute, metric and event,
// generated from the registry in obs/semconv/registry by `task semconv`. Upstream names (http.*,
// server.*, gen_ai.*) come from @opentelemetry/semantic-conventions. obs/semconv/names.go holds
// the same names for Go.

/**
 * The attribute justabill.aggregates.eligibility.
 *
 * Whether a user vote counts in the aggregates, or why not.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_AGGREGATES_ELIGIBILITY = "justabill.aggregates.eligibility";

/**
 * The justabill.aggregates.eligibility value "eligible".
 *
 * The vote counts.
 */
export const AGGREGATES_ELIGIBILITY_VALUE_ELIGIBLE = "eligible";

/**
 * The justabill.aggregates.eligibility value "young_account".
 *
 * The account is younger than the minimum age.
 */
export const AGGREGATES_ELIGIBILITY_VALUE_YOUNG_ACCOUNT = "young_account";

/**
 * The justabill.aggregates.eligibility value "app_check".
 *
 * The vote didn't pass App Check when it was cast.
 */
export const AGGREGATES_ELIGIBILITY_VALUE_APP_CHECK = "app_check";

/**
 * The justabill.aggregates.eligibility value "excluded".
 *
 * The account was excluded from the aggregates with the aggregates CLI.
 */
export const AGGREGATES_ELIGIBILITY_VALUE_EXCLUDED = "excluded";

/**
 * The attribute justabill.aggregates.hold_reason.
 *
 * The anomaly rule that put a cell on hold.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_AGGREGATES_HOLD_REASON = "justabill.aggregates.hold_reason";

/**
 * The justabill.aggregates.hold_reason value "burst".
 *
 * Votes in the last hour exceeded the burst factor times the trailing hourly mean.
 */
export const AGGREGATES_HOLD_REASON_VALUE_BURST = "burst";

/**
 * The justabill.aggregates.hold_reason value "young_accounts".
 *
 * Too many of the new votes since the last publish came from young accounts.
 */
export const AGGREGATES_HOLD_REASON_VALUE_YOUNG_ACCOUNTS = "young_accounts";

/**
 * The justabill.aggregates.hold_reason value "swing".
 *
 * The Yea share moved too far in one publish.
 */
export const AGGREGATES_HOLD_REASON_VALUE_SWING = "swing";

/**
 * The attribute justabill.aggregates.status.
 *
 * A vote_aggregates cell's status after a run.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_AGGREGATES_STATUS = "justabill.aggregates.status";

/**
 * The justabill.aggregates.status value "published".
 *
 * The cell shows its rounded numbers.
 */
export const AGGREGATES_STATUS_VALUE_PUBLISHED = "published";

/**
 * The justabill.aggregates.status value "suppressed".
 *
 * The cell has too few eligible votes, or was held before it was ever shown, and isn't served.
 */
export const AGGREGATES_STATUS_VALUE_SUPPRESSED = "suppressed";

/**
 * The justabill.aggregates.status value "held".
 *
 * The cell keeps its last published numbers under review.
 */
export const AGGREGATES_STATUS_VALUE_HELD = "held";

/**
 * The attribute justabill.app_check.mode.
 *
 * The API's APP_CHECK_MODE when the token was checked.
 *
 * Nothing is checked, or counted, when the mode is off.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_APP_CHECK_MODE = "justabill.app_check.mode";

/**
 * The justabill.app_check.mode value "audit".
 *
 * A failed check is recorded on the vote, and the request continues.
 */
export const APP_CHECK_MODE_VALUE_AUDIT = "audit";

/**
 * The justabill.app_check.mode value "enforce".
 *
 * A failed check rejects the request.
 */
export const APP_CHECK_MODE_VALUE_ENFORCE = "enforce";

/**
 * The attribute justabill.app_check.result.
 *
 * How an App Check token check ended.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_APP_CHECK_RESULT = "justabill.app_check.result";

/**
 * The justabill.app_check.result value "ok".
 *
 * The token was valid.
 */
export const APP_CHECK_RESULT_VALUE_OK = "ok";

/**
 * The justabill.app_check.result value "missing".
 *
 * The request had no App Check token.
 */
export const APP_CHECK_RESULT_VALUE_MISSING = "missing";

/**
 * The justabill.app_check.result value "invalid".
 *
 * The token was malformed, expired, or signed for another project.
 */
export const APP_CHECK_RESULT_VALUE_INVALID = "invalid";

/**
 * The justabill.app_check.result value "error".
 *
 * The token couldn't be checked, for example because Google's signing keys were unavailable.
 */
export const APP_CHECK_RESULT_VALUE_ERROR = "error";

/**
 * The attribute justabill.experiment.id.
 *
 * The experiment's id in the web app's experiment registry.
 *
 * One of the ids in web/src/lib/experiments/registry.ts, so its values are bounded. Never carries a user, bill or member ID.
 *
 * Type: string. Stability: development.
 */
export const ATTR_EXPERIMENT_ID = "justabill.experiment.id";

/**
 * The attribute justabill.experiment.variant.
 *
 * The arm of the experiment the visitor was shown.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_EXPERIMENT_VARIANT = "justabill.experiment.variant";

/**
 * The justabill.experiment.variant value "control".
 *
 * The page as it is without the experiment.
 */
export const EXPERIMENT_VARIANT_VALUE_CONTROL = "control";

/**
 * The justabill.experiment.variant value "treatment".
 *
 * The version of the page under test.
 */
export const EXPERIMENT_VARIANT_VALUE_TREATMENT = "treatment";

/**
 * The attribute justabill.item.outcome.
 *
 * What happened to one item in a pipeline job.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_ITEM_OUTCOME = "justabill.item.outcome";

/**
 * The justabill.item.outcome value "ok".
 *
 * The item was written.
 */
export const ITEM_OUTCOME_VALUE_OK = "ok";

/**
 * The justabill.item.outcome value "failed".
 *
 * The item failed and will be retried on a later run.
 */
export const ITEM_OUTCOME_VALUE_FAILED = "failed";

/**
 * The justabill.item.outcome value "skipped".
 *
 * The item was unchanged or out of scope, so nothing was written.
 */
export const ITEM_OUTCOME_VALUE_SKIPPED = "skipped";

/**
 * The attribute justabill.job.duration.
 *
 * How long a pipeline job run took, in seconds.
 *
 * Type: double. Stability: development.
 */
export const ATTR_JOB_DURATION = "justabill.job.duration";

/**
 * The attribute justabill.job.items.failed.
 *
 * The number of items a pipeline job run failed to process.
 *
 * Type: int. Stability: development.
 */
export const ATTR_JOB_ITEMS_FAILED = "justabill.job.items.failed";

/**
 * The attribute justabill.job.items.ok.
 *
 * The number of items a pipeline job run processed successfully.
 *
 * Type: int. Stability: development.
 */
export const ATTR_JOB_ITEMS_OK = "justabill.job.items.ok";

/**
 * The attribute justabill.job.name.
 *
 * The name of the pipeline job.
 *
 * One of the scheduler's job names. Never carries a bill, member or user ID.
 *
 * Type: string. Stability: development.
 */
export const ATTR_JOB_NAME = "justabill.job.name";

/**
 * The attribute justabill.job.outcome.
 *
 * How a pipeline job run ended.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_JOB_OUTCOME = "justabill.job.outcome";

/**
 * The justabill.job.outcome value "ok".
 *
 * The run returned no error before its deadline.
 */
export const JOB_OUTCOME_VALUE_OK = "ok";

/**
 * The justabill.job.outcome value "failed".
 *
 * The run returned an error.
 */
export const JOB_OUTCOME_VALUE_FAILED = "failed";

/**
 * The justabill.job.outcome value "timeout".
 *
 * The run passed the job's timeout.
 */
export const JOB_OUTCOME_VALUE_TIMEOUT = "timeout";

/**
 * The justabill.job.outcome value "canceled".
 *
 * The scheduler's context was canceled, as on shutdown.
 */
export const JOB_OUTCOME_VALUE_CANCELED = "canceled";

/**
 * The justabill.job.outcome value "unavailable".
 *
 * The job's upstream source was down, as for maintenance, and the job will try again soon.
 */
export const JOB_OUTCOME_VALUE_UNAVAILABLE = "unavailable";

/**
 * The attribute justabill.summary.outcome.
 *
 * How a summary or law-change explanation request to Gemini ended.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_SUMMARY_OUTCOME = "justabill.summary.outcome";

/**
 * The justabill.summary.outcome value "ok".
 *
 * The model returned a usable summary.
 */
export const SUMMARY_OUTCOME_VALUE_OK = "ok";

/**
 * The justabill.summary.outcome value "safety_blocked".
 *
 * The model's safety filters blocked the prompt or the response.
 */
export const SUMMARY_OUTCOME_VALUE_SAFETY_BLOCKED = "safety_blocked";

/**
 * The justabill.summary.outcome value "empty".
 *
 * The model returned no usable text.
 */
export const SUMMARY_OUTCOME_VALUE_EMPTY = "empty";

/**
 * The justabill.summary.outcome value "error".
 *
 * The request failed, for example with a network error or a 5xx.
 */
export const SUMMARY_OUTCOME_VALUE_ERROR = "error";

/**
 * The attribute justabill.vercel.alert.type.
 *
 * The type of a Vercel alert, as Vercel names it.
 *
 * Type: string. Stability: development.
 */
export const ATTR_VERCEL_ALERT_TYPE = "justabill.vercel.alert.type";

/**
 * The attribute justabill.vercel.deployment.state.
 *
 * The state of a Vercel deployment, as Vercel names it.
 *
 * Type: string. Stability: development.
 */
export const ATTR_VERCEL_DEPLOYMENT_STATE = "justabill.vercel.deployment.state";

/**
 * The attribute justabill.vercel.failure.kind.
 *
 * How a web function request failed, from Vercel's drain lines.
 *
 * Set by vercel-drain's counting rule (docs/design/473-vercel-function-failures.md). The alert reads crash and timeout; error overlaps http.server.request.duration on purpose.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_VERCEL_FAILURE_KIND = "justabill.vercel.failure.kind";

/**
 * The justabill.vercel.failure.kind value "crash".
 *
 * The function returned no response (statusCode -1) and the client didn't get a timeout.
 */
export const VERCEL_FAILURE_KIND_VALUE_CRASH = "crash";

/**
 * The justabill.vercel.failure.kind value "timeout".
 *
 * The client got 504, as on a function timeout.
 */
export const VERCEL_FAILURE_KIND_VALUE_TIMEOUT = "timeout";

/**
 * The justabill.vercel.failure.kind value "error".
 *
 * The client got another 5xx.
 */
export const VERCEL_FAILURE_KIND_VALUE_ERROR = "error";

/**
 * The justabill.vercel.failure.kind value "background".
 *
 * A background revalidation failed; the client got a cached page.
 */
export const VERCEL_FAILURE_KIND_VALUE_BACKGROUND = "background";

/**
 * The attribute justabill.vercel.line.outcome.
 *
 * What vercel-drain did with a log drain line.
 *
 * The first that applies: failure, repeat, ours, no_request_id, forwarded. Lines with no_request_id are forwarded but can't be counted as failures.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_VERCEL_LINE_OUTCOME = "justabill.vercel.line.outcome";

/**
 * The justabill.vercel.line.outcome value "failure".
 *
 * The line marked a failed request, counted in justabill.vercel.function.failures.
 */
export const VERCEL_LINE_OUTCOME_VALUE_FAILURE = "failure";

/**
 * The justabill.vercel.line.outcome value "repeat".
 *
 * The line marked a failed request this replica already counted in the last 15 minutes.
 */
export const VERCEL_LINE_OUTCOME_VALUE_REPEAT = "repeat";

/**
 * The justabill.vercel.line.outcome value "ours".
 *
 * A JSON line our own code already exported, dropped as a duplicate.
 */
export const VERCEL_LINE_OUTCOME_VALUE_OURS = "ours";

/**
 * The justabill.vercel.line.outcome value "no_request_id".
 *
 * A lambda line without a request ID, forwarded but never counted as a failure.
 */
export const VERCEL_LINE_OUTCOME_VALUE_NO_REQUEST_ID = "no_request_id";

/**
 * The justabill.vercel.line.outcome value "forwarded".
 *
 * The line was forwarded as a log record.
 */
export const VERCEL_LINE_OUTCOME_VALUE_FORWARDED = "forwarded";

/**
 * The attribute justabill.vercel.log.type.
 *
 * The output type of a Vercel log drain line (Vercel's type field).
 *
 * Vercel's documented values; anything else is _OTHER.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_VERCEL_LOG_TYPE = "justabill.vercel.log.type";

/**
 * The justabill.vercel.log.type value "command".
 *
 * Vercel's command output type.
 */
export const VERCEL_LOG_TYPE_VALUE_COMMAND = "command";

/**
 * The justabill.vercel.log.type value "stdout".
 *
 * Vercel's stdout output type.
 */
export const VERCEL_LOG_TYPE_VALUE_STDOUT = "stdout";

/**
 * The justabill.vercel.log.type value "stderr".
 *
 * Vercel's stderr output type.
 */
export const VERCEL_LOG_TYPE_VALUE_STDERR = "stderr";

/**
 * The justabill.vercel.log.type value "exit".
 *
 * Vercel's exit output type.
 */
export const VERCEL_LOG_TYPE_VALUE_EXIT = "exit";

/**
 * The justabill.vercel.log.type value "deployment-state".
 *
 * Vercel's deployment-state output type.
 */
export const VERCEL_LOG_TYPE_VALUE_DEPLOYMENT_STATE = "deployment-state";

/**
 * The justabill.vercel.log.type value "delimiter".
 *
 * Vercel's delimiter output type.
 */
export const VERCEL_LOG_TYPE_VALUE_DELIMITER = "delimiter";

/**
 * The justabill.vercel.log.type value "middleware".
 *
 * Vercel's middleware output type.
 */
export const VERCEL_LOG_TYPE_VALUE_MIDDLEWARE = "middleware";

/**
 * The justabill.vercel.log.type value "middleware-invocation".
 *
 * Vercel's middleware-invocation output type.
 */
export const VERCEL_LOG_TYPE_VALUE_MIDDLEWARE_INVOCATION = "middleware-invocation";

/**
 * The justabill.vercel.log.type value "edge-function-invocation".
 *
 * Vercel's edge-function-invocation output type.
 */
export const VERCEL_LOG_TYPE_VALUE_EDGE_FUNCTION_INVOCATION = "edge-function-invocation";

/**
 * The justabill.vercel.log.type value "metric".
 *
 * Vercel's metric output type.
 */
export const VERCEL_LOG_TYPE_VALUE_METRIC = "metric";

/**
 * The justabill.vercel.log.type value "report".
 *
 * Vercel's report output type.
 */
export const VERCEL_LOG_TYPE_VALUE_REPORT = "report";

/**
 * The justabill.vercel.log.type value "fatal".
 *
 * Vercel's fatal output type.
 */
export const VERCEL_LOG_TYPE_VALUE_FATAL = "fatal";

/**
 * The justabill.vercel.log.type value "_OTHER".
 *
 * A type Vercel doesn't document, or none.
 */
export const VERCEL_LOG_TYPE_VALUE_OTHER = "_OTHER";

/**
 * The attribute justabill.vercel.request.id.
 *
 * Vercel's ID for the request a drain line belongs to, for finding it in Vercel's dashboard.
 *
 * Type: string. Stability: development.
 */
export const ATTR_VERCEL_REQUEST_ID = "justabill.vercel.request.id";

/**
 * The attribute justabill.vercel.source.
 *
 * Where a Vercel log drain line came from, as Vercel names it.
 *
 * Type: string. Stability: development.
 */
export const ATTR_VERCEL_SOURCE = "justabill.vercel.source";

/**
 * The attribute justabill.vercel.status_class.
 *
 * The class of a drain line's own statusCode.
 *
 * Type: enum. Stability: development.
 */
export const ATTR_VERCEL_STATUS_CLASS = "justabill.vercel.status_class";

/**
 * The justabill.vercel.status_class value "-1".
 *
 * statusCode -1, meaning no response returned and the function crashed.
 */
export const VERCEL_STATUS_CLASS_VALUE_NO_RESPONSE = "-1";

/**
 * The justabill.vercel.status_class value "1xx".
 *
 * A 1xx status.
 */
export const VERCEL_STATUS_CLASS_VALUE_STATUS_1XX = "1xx";

/**
 * The justabill.vercel.status_class value "2xx".
 *
 * A 2xx status.
 */
export const VERCEL_STATUS_CLASS_VALUE_STATUS_2XX = "2xx";

/**
 * The justabill.vercel.status_class value "3xx".
 *
 * A 3xx status.
 */
export const VERCEL_STATUS_CLASS_VALUE_STATUS_3XX = "3xx";

/**
 * The justabill.vercel.status_class value "4xx".
 *
 * A 4xx status.
 */
export const VERCEL_STATUS_CLASS_VALUE_STATUS_4XX = "4xx";

/**
 * The justabill.vercel.status_class value "5xx".
 *
 * A 5xx status.
 */
export const VERCEL_STATUS_CLASS_VALUE_STATUS_5XX = "5xx";

/**
 * The justabill.vercel.status_class value "none".
 *
 * No statusCode, or one outside -1 and 100-599.
 */
export const VERCEL_STATUS_CLASS_VALUE_NONE = "none";

/**
 * The metric justabill.aggregates.cells.
 *
 * vote_aggregates cells after the latest aggregate-votes run, by status.
 *
 * Instrument: gauge. Unit: {cell}. Stability: development.
 *
 * Attributes:
 *   - justabill.aggregates.status (required)
 */
export const METRIC_AGGREGATES_CELLS = "justabill.aggregates.cells";

/** The UCUM unit of justabill.aggregates.cells. */
export const METRIC_AGGREGATES_CELLS_UNIT = "{cell}";

/** The description of justabill.aggregates.cells. */
export const METRIC_AGGREGATES_CELLS_DESCRIPTION = "vote_aggregates cells after the latest aggregate-votes run, by status.";

/**
 * The metric justabill.aggregates.holds.
 *
 * Cells the aggregate-votes job put on hold, by the rule that tripped.
 *
 * Each new hold should raise an alert (docs/design/89-aggregate-analytics.md).
 *
 * Instrument: counter. Unit: {cell}. Stability: development.
 *
 * Attributes:
 *   - justabill.aggregates.hold_reason (required)
 */
export const METRIC_AGGREGATES_HOLDS = "justabill.aggregates.holds";

/** The UCUM unit of justabill.aggregates.holds. */
export const METRIC_AGGREGATES_HOLDS_UNIT = "{cell}";

/** The description of justabill.aggregates.holds. */
export const METRIC_AGGREGATES_HOLDS_DESCRIPTION = "Cells the aggregate-votes job put on hold, by the rule that tripped.";

/**
 * The metric justabill.aggregates.votes.
 *
 * Yea and Nay user votes in the latest aggregate-votes snapshot, by eligibility.
 *
 * Carries no user, bill or place.
 *
 * Instrument: gauge. Unit: {vote}. Stability: development.
 *
 * Attributes:
 *   - justabill.aggregates.eligibility (required)
 */
export const METRIC_AGGREGATES_VOTES = "justabill.aggregates.votes";

/** The UCUM unit of justabill.aggregates.votes. */
export const METRIC_AGGREGATES_VOTES_UNIT = "{vote}";

/** The description of justabill.aggregates.votes. */
export const METRIC_AGGREGATES_VOTES_DESCRIPTION = "Yea and Nay user votes in the latest aggregate-votes snapshot, by eligibility.";

/**
 * The metric justabill.app_check.verifications.
 *
 * App Check token checks on the API's vote and import routes, by result.
 *
 * Counted only when APP_CHECK_MODE is audit or enforce. Carries no user, token or IP. The failure-rate alert (docs/design/89-aggregate-analytics.md) is built on it.
 *
 * Instrument: counter. Unit: {verification}. Stability: development.
 *
 * Attributes:
 *   - justabill.app_check.mode (required)
 *   - justabill.app_check.result (required)
 */
export const METRIC_APP_CHECK_VERIFICATIONS = "justabill.app_check.verifications";

/** The UCUM unit of justabill.app_check.verifications. */
export const METRIC_APP_CHECK_VERIFICATIONS_UNIT = "{verification}";

/** The description of justabill.app_check.verifications. */
export const METRIC_APP_CHECK_VERIFICATIONS_DESCRIPTION = "App Check token checks on the API's vote and import routes, by result.";

/**
 * The metric justabill.experiment.conversions.
 *
 * Visitors who took an experiment's goal action, by arm.
 *
 * An action such as casting a vote, never how anyone voted. Sent once per visitor and experiment, and only after that visitor's exposure.
 *
 * Instrument: counter. Unit: {visitor}. Stability: development.
 *
 * Attributes:
 *   - justabill.experiment.id (required)
 *   - justabill.experiment.variant (required)
 */
export const METRIC_EXPERIMENT_CONVERSIONS = "justabill.experiment.conversions";

/** The UCUM unit of justabill.experiment.conversions. */
export const METRIC_EXPERIMENT_CONVERSIONS_UNIT = "{visitor}";

/** The description of justabill.experiment.conversions. */
export const METRIC_EXPERIMENT_CONVERSIONS_DESCRIPTION = "Visitors who took an experiment's goal action, by arm.";

/**
 * The metric justabill.experiment.exposures.
 *
 * Visitors who saw an experiment's page, by arm.
 *
 * The browser sends one exposure per visitor and experiment to POST /api/experiments, which takes the arm from the visitor's jab_exp cookie (docs/design/580-ab-experiments.md).
 *
 * Instrument: counter. Unit: {visitor}. Stability: development.
 *
 * Attributes:
 *   - justabill.experiment.id (required)
 *   - justabill.experiment.variant (required)
 */
export const METRIC_EXPERIMENT_EXPOSURES = "justabill.experiment.exposures";

/** The UCUM unit of justabill.experiment.exposures. */
export const METRIC_EXPERIMENT_EXPOSURES_UNIT = "{visitor}";

/** The description of justabill.experiment.exposures. */
export const METRIC_EXPERIMENT_EXPOSURES_DESCRIPTION = "Visitors who saw an experiment's page, by arm.";

/**
 * The metric justabill.law_change.results.
 *
 * Law-change explanation requests to Gemini, by outcome.
 *
 * One request explains every section of law a bill changes (sync-law-changes). Counted apart from justabill.summary.results so that the summary failure alert and dashboard measure bill and diff summaries only; gen_ai.client.token.usage and gen_ai.client.operation.duration count both.
 *
 * Instrument: counter. Unit: {request}. Stability: development.
 *
 * Attributes:
 *   - gen_ai.request.model (required)
 *   - justabill.summary.outcome (required)
 */
export const METRIC_LAW_CHANGE_RESULTS = "justabill.law_change.results";

/** The UCUM unit of justabill.law_change.results. */
export const METRIC_LAW_CHANGE_RESULTS_UNIT = "{request}";

/** The description of justabill.law_change.results. */
export const METRIC_LAW_CHANGE_RESULTS_DESCRIPTION = "Law-change explanation requests to Gemini, by outcome.";

/**
 * The metric justabill.pipeline.items.
 *
 * Items handled by pipeline jobs, by outcome.
 *
 * Instrument: counter. Unit: {item}. Stability: development.
 *
 * Attributes:
 *   - justabill.item.outcome (required)
 *   - justabill.job.name (required)
 */
export const METRIC_PIPELINE_ITEMS = "justabill.pipeline.items";

/** The UCUM unit of justabill.pipeline.items. */
export const METRIC_PIPELINE_ITEMS_UNIT = "{item}";

/** The description of justabill.pipeline.items. */
export const METRIC_PIPELINE_ITEMS_DESCRIPTION = "Items handled by pipeline jobs, by outcome.";

/**
 * The metric justabill.pipeline.job.duration.
 *
 * How long pipeline job runs take.
 *
 * Instrument: histogram. Unit: s. Stability: development.
 *
 * Attributes:
 *   - justabill.job.name (required)
 *   - justabill.job.outcome (required)
 */
export const METRIC_PIPELINE_JOB_DURATION = "justabill.pipeline.job.duration";

/** The UCUM unit of justabill.pipeline.job.duration. */
export const METRIC_PIPELINE_JOB_DURATION_UNIT = "s";

/** The description of justabill.pipeline.job.duration. */
export const METRIC_PIPELINE_JOB_DURATION_DESCRIPTION = "How long pipeline job runs take.";

/**
 * The metric justabill.pipeline.job.last_success.
 *
 * When a pipeline job last finished successfully, as Unix time in seconds.
 *
 * Instrument: gauge. Unit: s. Stability: development.
 *
 * Attributes:
 *   - justabill.job.name (required)
 */
export const METRIC_PIPELINE_JOB_LAST_SUCCESS = "justabill.pipeline.job.last_success";

/** The UCUM unit of justabill.pipeline.job.last_success. */
export const METRIC_PIPELINE_JOB_LAST_SUCCESS_UNIT = "s";

/** The description of justabill.pipeline.job.last_success. */
export const METRIC_PIPELINE_JOB_LAST_SUCCESS_DESCRIPTION = "When a pipeline job last finished successfully, as Unix time in seconds.";

/**
 * The metric justabill.summary.results.
 *
 * Bill summary requests to Gemini, by outcome.
 *
 * Instrument: counter. Unit: {summary}. Stability: development.
 *
 * Attributes:
 *   - gen_ai.request.model (required)
 *   - justabill.summary.outcome (required)
 */
export const METRIC_SUMMARY_RESULTS = "justabill.summary.results";

/** The UCUM unit of justabill.summary.results. */
export const METRIC_SUMMARY_RESULTS_UNIT = "{summary}";

/** The description of justabill.summary.results. */
export const METRIC_SUMMARY_RESULTS_DESCRIPTION = "Bill summary requests to Gemini, by outcome.";

/**
 * The metric justabill.upstream.quota.remaining.
 *
 * Requests left in the upstream API's rate-limit window.
 *
 * Read from the `X-RateLimit-Remaining` response header of Congress.gov and GovInfo.
 *
 * Instrument: gauge. Unit: {request}. Stability: development.
 *
 * Attributes:
 *   - server.address (required)
 */
export const METRIC_UPSTREAM_QUOTA_REMAINING = "justabill.upstream.quota.remaining";

/** The UCUM unit of justabill.upstream.quota.remaining. */
export const METRIC_UPSTREAM_QUOTA_REMAINING_UNIT = "{request}";

/** The description of justabill.upstream.quota.remaining. */
export const METRIC_UPSTREAM_QUOTA_REMAINING_DESCRIPTION = "Requests left in the upstream API's rate-limit window.";

/**
 * The metric justabill.vercel.drain.lag.
 *
 * How long after its timestamp a Vercel log drain line reached vercel-drain.
 *
 * Instrument: histogram. Unit: s. Stability: development.
 *
 * Attributes:
 *   - justabill.vercel.source (required)
 */
export const METRIC_VERCEL_DRAIN_LAG = "justabill.vercel.drain.lag";

/** The UCUM unit of justabill.vercel.drain.lag. */
export const METRIC_VERCEL_DRAIN_LAG_UNIT = "s";

/** The description of justabill.vercel.drain.lag. */
export const METRIC_VERCEL_DRAIN_LAG_DESCRIPTION = "How long after its timestamp a Vercel log drain line reached vercel-drain.";

/**
 * The metric justabill.vercel.drain.lines.
 *
 * Vercel log drain lines vercel-drain received, by shape and outcome.
 *
 * The census that checks the failure counting rule against production data (design 473).
 *
 * Instrument: counter. Unit: {line}. Stability: development.
 *
 * Attributes:
 *   - justabill.vercel.line.outcome (required)
 *   - justabill.vercel.log.type (required)
 *   - justabill.vercel.source (required)
 *   - justabill.vercel.status_class (required)
 */
export const METRIC_VERCEL_DRAIN_LINES = "justabill.vercel.drain.lines";

/** The UCUM unit of justabill.vercel.drain.lines. */
export const METRIC_VERCEL_DRAIN_LINES_UNIT = "{line}";

/** The description of justabill.vercel.drain.lines. */
export const METRIC_VERCEL_DRAIN_LINES_DESCRIPTION = "Vercel log drain lines vercel-drain received, by shape and outcome.";

/**
 * The metric justabill.vercel.function.failures.
 *
 * Web function requests that crashed, timed out or failed, counted once each from Vercel's drain lines.
 *
 * Deduplicated by Vercel's request ID for 15 minutes on each vercel-drain replica, so a request whose lines reach both replicas can count twice. Carries no path, host, request ID or IP. Design docs/design/473-vercel-function-failures.md.
 *
 * Instrument: counter. Unit: {request}. Stability: development.
 *
 * Attributes:
 *   - http.response.status_code ({"conditionally_required": "When the line carries a valid HTTP status."})
 *   - justabill.vercel.failure.kind (required)
 */
export const METRIC_VERCEL_FUNCTION_FAILURES = "justabill.vercel.function.failures";

/** The UCUM unit of justabill.vercel.function.failures. */
export const METRIC_VERCEL_FUNCTION_FAILURES_UNIT = "{request}";

/** The description of justabill.vercel.function.failures. */
export const METRIC_VERCEL_FUNCTION_FAILURES_DESCRIPTION = "Web function requests that crashed, timed out or failed, counted once each from Vercel's drain lines.";

/**
 * The metric justabill.web.fixture_fallback.
 *
 * Pages the web app rendered from example fixtures because the API call failed.
 *
 * Counted in `api.ts` until #73 removes the fixture fallback in production.
 *
 * Instrument: counter. Unit: {render}. Stability: development.
 *
 * Attributes:
 *   - http.route (required)
 */
export const METRIC_WEB_FIXTURE_FALLBACK = "justabill.web.fixture_fallback";

/** The UCUM unit of justabill.web.fixture_fallback. */
export const METRIC_WEB_FIXTURE_FALLBACK_UNIT = "{render}";

/** The description of justabill.web.fixture_fallback. */
export const METRIC_WEB_FIXTURE_FALLBACK_DESCRIPTION = "Pages the web app rendered from example fixtures because the API call failed.";

/**
 * The event name justabill.pipeline.job.finished.
 *
 * A pipeline job run finished.
 *
 * Emitted once per run by the scheduler and backfill, whatever the outcome.
 *
 * Stability: development.
 *
 * Attributes:
 *   - justabill.job.duration (required)
 *   - justabill.job.items.failed (recommended)
 *   - justabill.job.items.ok (recommended)
 *   - justabill.job.name (required)
 *   - justabill.job.outcome (required)
 */
export const EVENT_PIPELINE_JOB_FINISHED = "justabill.pipeline.job.finished";

/**
 * The event name justabill.vercel.alert.
 *
 * Vercel raised an alert, such as a usage or error anomaly, forwarded by vercel-drain.
 *
 * Stability: development.
 *
 * Attributes:
 *   - justabill.vercel.alert.type (required)
 */
export const EVENT_VERCEL_ALERT = "justabill.vercel.alert";

/**
 * The event name justabill.vercel.deployment.
 *
 * A Vercel deployment changed state, forwarded by vercel-drain.
 *
 * Stability: development.
 *
 * Attributes:
 *   - justabill.vercel.deployment.state (required)
 */
export const EVENT_VERCEL_DEPLOYMENT = "justabill.vercel.deployment";
