// Code generated by weaver from obs/semconv/registry; DO NOT EDIT.

// Package semconv holds the names of Just a Bill's own telemetry: every justabill.* attribute,
// metric and event, generated from the registry in obs/semconv/registry by `task semconv`.
// Upstream names (http.*, server.*, gen_ai.*) come from go.opentelemetry.io/otel/semconv.
// web/src/lib/obs/names.ts holds the same names for TypeScript.
package semconv

import "go.opentelemetry.io/otel/attribute"

// AggregatesEligibilityKey is the attribute justabill.aggregates.eligibility.
//
// Whether a user vote counts in the aggregates, or why not.
//
// Type: enum. Stability: development.
const AggregatesEligibilityKey = attribute.Key("justabill.aggregates.eligibility")

// AggregatesEligibilityEligible is the justabill.aggregates.eligibility value "eligible".
//
// The vote counts.
const AggregatesEligibilityEligible = "eligible"

// AggregatesEligibilityYoungAccount is the justabill.aggregates.eligibility value "young_account".
//
// The account is younger than the minimum age.
const AggregatesEligibilityYoungAccount = "young_account"

// AggregatesEligibilityAppCheck is the justabill.aggregates.eligibility value "app_check".
//
// The vote didn't pass App Check when it was cast.
const AggregatesEligibilityAppCheck = "app_check"

// AggregatesEligibilityExcluded is the justabill.aggregates.eligibility value "excluded".
//
// The account was excluded from the aggregates with the aggregates CLI.
const AggregatesEligibilityExcluded = "excluded"

// AggregatesHoldReasonKey is the attribute justabill.aggregates.hold_reason.
//
// The anomaly rule that put a cell on hold.
//
// Type: enum. Stability: development.
const AggregatesHoldReasonKey = attribute.Key("justabill.aggregates.hold_reason")

// AggregatesHoldReasonBurst is the justabill.aggregates.hold_reason value "burst".
//
// Votes in the last hour exceeded the burst factor times the trailing hourly mean.
const AggregatesHoldReasonBurst = "burst"

// AggregatesHoldReasonYoungAccounts is the justabill.aggregates.hold_reason value "young_accounts".
//
// Too many of the new votes since the last publish came from young accounts.
const AggregatesHoldReasonYoungAccounts = "young_accounts"

// AggregatesHoldReasonSwing is the justabill.aggregates.hold_reason value "swing".
//
// The Yea share moved too far in one publish.
const AggregatesHoldReasonSwing = "swing"

// AggregatesStatusKey is the attribute justabill.aggregates.status.
//
// A vote_aggregates cell's status after a run.
//
// Type: enum. Stability: development.
const AggregatesStatusKey = attribute.Key("justabill.aggregates.status")

// AggregatesStatusPublished is the justabill.aggregates.status value "published".
//
// The cell shows its rounded numbers.
const AggregatesStatusPublished = "published"

// AggregatesStatusSuppressed is the justabill.aggregates.status value "suppressed".
//
// The cell has too few eligible votes, or was held before it was ever shown, and isn't served.
const AggregatesStatusSuppressed = "suppressed"

// AggregatesStatusHeld is the justabill.aggregates.status value "held".
//
// The cell keeps its last published numbers under review.
const AggregatesStatusHeld = "held"

// AppCheckModeKey is the attribute justabill.app_check.mode.
//
// The API's APP_CHECK_MODE when the token was checked.
//
// Nothing is checked, or counted, when the mode is off.
//
// Type: enum. Stability: development.
const AppCheckModeKey = attribute.Key("justabill.app_check.mode")

// AppCheckModeAudit is the justabill.app_check.mode value "audit".
//
// A failed check is recorded on the vote, and the request continues.
const AppCheckModeAudit = "audit"

// AppCheckModeEnforce is the justabill.app_check.mode value "enforce".
//
// A failed check rejects the request.
const AppCheckModeEnforce = "enforce"

// AppCheckResultKey is the attribute justabill.app_check.result.
//
// How an App Check token check ended.
//
// Type: enum. Stability: development.
const AppCheckResultKey = attribute.Key("justabill.app_check.result")

// AppCheckResultOK is the justabill.app_check.result value "ok".
//
// The token was valid.
const AppCheckResultOK = "ok"

// AppCheckResultMissing is the justabill.app_check.result value "missing".
//
// The request had no App Check token.
const AppCheckResultMissing = "missing"

// AppCheckResultInvalid is the justabill.app_check.result value "invalid".
//
// The token was malformed, expired, or signed for another project.
const AppCheckResultInvalid = "invalid"

// AppCheckResultError is the justabill.app_check.result value "error".
//
// The token couldn't be checked, for example because Google's signing keys were unavailable.
const AppCheckResultError = "error"

// ExperimentIDKey is the attribute justabill.experiment.id.
//
// The experiment's id in the web app's experiment registry.
//
// One of the ids in web/src/lib/experiments/registry.ts, so its values are bounded. Never carries a user, bill or member ID.
//
// Type: string. Stability: development.
const ExperimentIDKey = attribute.Key("justabill.experiment.id")

// ExperimentVariantKey is the attribute justabill.experiment.variant.
//
// The arm of the experiment the visitor was shown.
//
// Type: enum. Stability: development.
const ExperimentVariantKey = attribute.Key("justabill.experiment.variant")

// ExperimentVariantControl is the justabill.experiment.variant value "control".
//
// The page as it is without the experiment.
const ExperimentVariantControl = "control"

// ExperimentVariantTreatment is the justabill.experiment.variant value "treatment".
//
// The version of the page under test.
const ExperimentVariantTreatment = "treatment"

// ItemOutcomeKey is the attribute justabill.item.outcome.
//
// What happened to one item in a pipeline job.
//
// Type: enum. Stability: development.
const ItemOutcomeKey = attribute.Key("justabill.item.outcome")

// ItemOutcomeOK is the justabill.item.outcome value "ok".
//
// The item was written.
const ItemOutcomeOK = "ok"

// ItemOutcomeFailed is the justabill.item.outcome value "failed".
//
// The item failed and will be retried on a later run.
const ItemOutcomeFailed = "failed"

// ItemOutcomeSkipped is the justabill.item.outcome value "skipped".
//
// The item was unchanged or out of scope, so nothing was written.
const ItemOutcomeSkipped = "skipped"

// JobDurationKey is the attribute justabill.job.duration.
//
// How long a pipeline job run took, in seconds.
//
// Type: double. Stability: development.
const JobDurationKey = attribute.Key("justabill.job.duration")

// JobItemsFailedKey is the attribute justabill.job.items.failed.
//
// The number of items a pipeline job run failed to process.
//
// Type: int. Stability: development.
const JobItemsFailedKey = attribute.Key("justabill.job.items.failed")

// JobItemsOKKey is the attribute justabill.job.items.ok.
//
// The number of items a pipeline job run processed successfully.
//
// Type: int. Stability: development.
const JobItemsOKKey = attribute.Key("justabill.job.items.ok")

// JobNameKey is the attribute justabill.job.name.
//
// The name of the pipeline job.
//
// One of the scheduler's job names. Never carries a bill, member or user ID.
//
// Type: string. Stability: development.
const JobNameKey = attribute.Key("justabill.job.name")

// JobOutcomeKey is the attribute justabill.job.outcome.
//
// How a pipeline job run ended.
//
// Type: enum. Stability: development.
const JobOutcomeKey = attribute.Key("justabill.job.outcome")

// JobOutcomeOK is the justabill.job.outcome value "ok".
//
// The run returned no error before its deadline.
const JobOutcomeOK = "ok"

// JobOutcomeFailed is the justabill.job.outcome value "failed".
//
// The run returned an error.
const JobOutcomeFailed = "failed"

// JobOutcomeTimeout is the justabill.job.outcome value "timeout".
//
// The run passed the job's timeout.
const JobOutcomeTimeout = "timeout"

// JobOutcomeCanceled is the justabill.job.outcome value "canceled".
//
// The scheduler's context was canceled, as on shutdown.
const JobOutcomeCanceled = "canceled"

// JobOutcomeUnavailable is the justabill.job.outcome value "unavailable".
//
// The job's upstream source was down, as for maintenance, and the job will try again soon.
const JobOutcomeUnavailable = "unavailable"

// SummaryOutcomeKey is the attribute justabill.summary.outcome.
//
// How a summary or law-change explanation request to Gemini ended.
//
// Type: enum. Stability: development.
const SummaryOutcomeKey = attribute.Key("justabill.summary.outcome")

// SummaryOutcomeOK is the justabill.summary.outcome value "ok".
//
// The model returned a usable summary.
const SummaryOutcomeOK = "ok"

// SummaryOutcomeSafetyBlocked is the justabill.summary.outcome value "safety_blocked".
//
// The model's safety filters blocked the prompt or the response.
const SummaryOutcomeSafetyBlocked = "safety_blocked"

// SummaryOutcomeEmpty is the justabill.summary.outcome value "empty".
//
// The model returned no usable text.
const SummaryOutcomeEmpty = "empty"

// SummaryOutcomeError is the justabill.summary.outcome value "error".
//
// The request failed, for example with a network error or a 5xx.
const SummaryOutcomeError = "error"

// VercelAlertTypeKey is the attribute justabill.vercel.alert.type.
//
// The type of a Vercel alert, as Vercel names it.
//
// Type: string. Stability: development.
const VercelAlertTypeKey = attribute.Key("justabill.vercel.alert.type")

// VercelDeploymentStateKey is the attribute justabill.vercel.deployment.state.
//
// The state of a Vercel deployment, as Vercel names it.
//
// Type: string. Stability: development.
const VercelDeploymentStateKey = attribute.Key("justabill.vercel.deployment.state")

// VercelFailureKindKey is the attribute justabill.vercel.failure.kind.
//
// How a web function request failed, from Vercel's drain lines.
//
// Set by vercel-drain's counting rule (docs/design/473-vercel-function-failures.md). The alert reads crash and timeout; error overlaps http.server.request.duration on purpose.
//
// Type: enum. Stability: development.
const VercelFailureKindKey = attribute.Key("justabill.vercel.failure.kind")

// VercelFailureKindCrash is the justabill.vercel.failure.kind value "crash".
//
// The function returned no response (statusCode -1) and the client didn't get a timeout.
const VercelFailureKindCrash = "crash"

// VercelFailureKindTimeout is the justabill.vercel.failure.kind value "timeout".
//
// The client got 504, as on a function timeout.
const VercelFailureKindTimeout = "timeout"

// VercelFailureKindError is the justabill.vercel.failure.kind value "error".
//
// The client got another 5xx.
const VercelFailureKindError = "error"

// VercelFailureKindBackground is the justabill.vercel.failure.kind value "background".
//
// A background revalidation failed; the client got a cached page.
const VercelFailureKindBackground = "background"

// VercelLineOutcomeKey is the attribute justabill.vercel.line.outcome.
//
// What vercel-drain did with a log drain line.
//
// The first that applies: failure, repeat, ours, no_request_id, forwarded. Lines with no_request_id are forwarded but can't be counted as failures.
//
// Type: enum. Stability: development.
const VercelLineOutcomeKey = attribute.Key("justabill.vercel.line.outcome")

// VercelLineOutcomeFailure is the justabill.vercel.line.outcome value "failure".
//
// The line marked a failed request, counted in justabill.vercel.function.failures.
const VercelLineOutcomeFailure = "failure"

// VercelLineOutcomeRepeat is the justabill.vercel.line.outcome value "repeat".
//
// The line marked a failed request this replica already counted in the last 15 minutes.
const VercelLineOutcomeRepeat = "repeat"

// VercelLineOutcomeOurs is the justabill.vercel.line.outcome value "ours".
//
// A JSON line our own code already exported, dropped as a duplicate.
const VercelLineOutcomeOurs = "ours"

// VercelLineOutcomeNoRequestId is the justabill.vercel.line.outcome value "no_request_id".
//
// A lambda line without a request ID, forwarded but never counted as a failure.
const VercelLineOutcomeNoRequestId = "no_request_id"

// VercelLineOutcomeForwarded is the justabill.vercel.line.outcome value "forwarded".
//
// The line was forwarded as a log record.
const VercelLineOutcomeForwarded = "forwarded"

// VercelLogTypeKey is the attribute justabill.vercel.log.type.
//
// The output type of a Vercel log drain line (Vercel's type field).
//
// Vercel's documented values; anything else is _OTHER.
//
// Type: enum. Stability: development.
const VercelLogTypeKey = attribute.Key("justabill.vercel.log.type")

// VercelLogTypeCommand is the justabill.vercel.log.type value "command".
//
// Vercel's command output type.
const VercelLogTypeCommand = "command"

// VercelLogTypeStdout is the justabill.vercel.log.type value "stdout".
//
// Vercel's stdout output type.
const VercelLogTypeStdout = "stdout"

// VercelLogTypeStderr is the justabill.vercel.log.type value "stderr".
//
// Vercel's stderr output type.
const VercelLogTypeStderr = "stderr"

// VercelLogTypeExit is the justabill.vercel.log.type value "exit".
//
// Vercel's exit output type.
const VercelLogTypeExit = "exit"

// VercelLogTypeDeploymentState is the justabill.vercel.log.type value "deployment-state".
//
// Vercel's deployment-state output type.
const VercelLogTypeDeploymentState = "deployment-state"

// VercelLogTypeDelimiter is the justabill.vercel.log.type value "delimiter".
//
// Vercel's delimiter output type.
const VercelLogTypeDelimiter = "delimiter"

// VercelLogTypeMiddleware is the justabill.vercel.log.type value "middleware".
//
// Vercel's middleware output type.
const VercelLogTypeMiddleware = "middleware"

// VercelLogTypeMiddlewareInvocation is the justabill.vercel.log.type value "middleware-invocation".
//
// Vercel's middleware-invocation output type.
const VercelLogTypeMiddlewareInvocation = "middleware-invocation"

// VercelLogTypeEdgeFunctionInvocation is the justabill.vercel.log.type value "edge-function-invocation".
//
// Vercel's edge-function-invocation output type.
const VercelLogTypeEdgeFunctionInvocation = "edge-function-invocation"

// VercelLogTypeMetric is the justabill.vercel.log.type value "metric".
//
// Vercel's metric output type.
const VercelLogTypeMetric = "metric"

// VercelLogTypeReport is the justabill.vercel.log.type value "report".
//
// Vercel's report output type.
const VercelLogTypeReport = "report"

// VercelLogTypeFatal is the justabill.vercel.log.type value "fatal".
//
// Vercel's fatal output type.
const VercelLogTypeFatal = "fatal"

// VercelLogTypeOther is the justabill.vercel.log.type value "_OTHER".
//
// A type Vercel doesn't document, or none.
const VercelLogTypeOther = "_OTHER"

// VercelRequestIDKey is the attribute justabill.vercel.request.id.
//
// Vercel's ID for the request a drain line belongs to, for finding it in Vercel's dashboard.
//
// Type: string. Stability: development.
const VercelRequestIDKey = attribute.Key("justabill.vercel.request.id")

// VercelSourceKey is the attribute justabill.vercel.source.
//
// Where a Vercel log drain line came from, as Vercel names it.
//
// Type: string. Stability: development.
const VercelSourceKey = attribute.Key("justabill.vercel.source")

// VercelStatusClassKey is the attribute justabill.vercel.status_class.
//
// The class of a drain line's own statusCode.
//
// Type: enum. Stability: development.
const VercelStatusClassKey = attribute.Key("justabill.vercel.status_class")

// VercelStatusClassNoResponse is the justabill.vercel.status_class value "-1".
//
// statusCode -1, meaning no response returned and the function crashed.
const VercelStatusClassNoResponse = "-1"

// VercelStatusClassStatus1xx is the justabill.vercel.status_class value "1xx".
//
// A 1xx status.
const VercelStatusClassStatus1xx = "1xx"

// VercelStatusClassStatus2xx is the justabill.vercel.status_class value "2xx".
//
// A 2xx status.
const VercelStatusClassStatus2xx = "2xx"

// VercelStatusClassStatus3xx is the justabill.vercel.status_class value "3xx".
//
// A 3xx status.
const VercelStatusClassStatus3xx = "3xx"

// VercelStatusClassStatus4xx is the justabill.vercel.status_class value "4xx".
//
// A 4xx status.
const VercelStatusClassStatus4xx = "4xx"

// VercelStatusClassStatus5xx is the justabill.vercel.status_class value "5xx".
//
// A 5xx status.
const VercelStatusClassStatus5xx = "5xx"

// VercelStatusClassNone is the justabill.vercel.status_class value "none".
//
// No statusCode, or one outside -1 and 100-599.
const VercelStatusClassNone = "none"

// AggregatesCellsName is the metric justabill.aggregates.cells.
//
// vote_aggregates cells after the latest aggregate-votes run, by status.
//
// Instrument: gauge. Unit: {cell}. Stability: development.
//
// Attributes:
//   - justabill.aggregates.status (required)
const AggregatesCellsName = "justabill.aggregates.cells"

// AggregatesCellsUnit is the UCUM unit of justabill.aggregates.cells.
const AggregatesCellsUnit = "{cell}"

// AggregatesCellsDescription is the description of justabill.aggregates.cells.
const AggregatesCellsDescription = "vote_aggregates cells after the latest aggregate-votes run, by status."

// AggregatesHoldsName is the metric justabill.aggregates.holds.
//
// Cells the aggregate-votes job put on hold, by the rule that tripped.
//
// Each new hold should raise an alert (docs/design/89-aggregate-analytics.md).
//
// Instrument: counter. Unit: {cell}. Stability: development.
//
// Attributes:
//   - justabill.aggregates.hold_reason (required)
const AggregatesHoldsName = "justabill.aggregates.holds"

// AggregatesHoldsUnit is the UCUM unit of justabill.aggregates.holds.
const AggregatesHoldsUnit = "{cell}"

// AggregatesHoldsDescription is the description of justabill.aggregates.holds.
const AggregatesHoldsDescription = "Cells the aggregate-votes job put on hold, by the rule that tripped."

// AggregatesVotesName is the metric justabill.aggregates.votes.
//
// Yea and Nay user votes in the latest aggregate-votes snapshot, by eligibility.
//
// Carries no user, bill or place.
//
// Instrument: gauge. Unit: {vote}. Stability: development.
//
// Attributes:
//   - justabill.aggregates.eligibility (required)
const AggregatesVotesName = "justabill.aggregates.votes"

// AggregatesVotesUnit is the UCUM unit of justabill.aggregates.votes.
const AggregatesVotesUnit = "{vote}"

// AggregatesVotesDescription is the description of justabill.aggregates.votes.
const AggregatesVotesDescription = "Yea and Nay user votes in the latest aggregate-votes snapshot, by eligibility."

// AppCheckVerificationsName is the metric justabill.app_check.verifications.
//
// App Check token checks on the API's vote and import routes, by result.
//
// Counted only when APP_CHECK_MODE is audit or enforce. Carries no user, token or IP. The failure-rate alert (docs/design/89-aggregate-analytics.md) is built on it.
//
// Instrument: counter. Unit: {verification}. Stability: development.
//
// Attributes:
//   - justabill.app_check.mode (required)
//   - justabill.app_check.result (required)
const AppCheckVerificationsName = "justabill.app_check.verifications"

// AppCheckVerificationsUnit is the UCUM unit of justabill.app_check.verifications.
const AppCheckVerificationsUnit = "{verification}"

// AppCheckVerificationsDescription is the description of justabill.app_check.verifications.
const AppCheckVerificationsDescription = "App Check token checks on the API's vote and import routes, by result."

// ExperimentConversionsName is the metric justabill.experiment.conversions.
//
// Visitors who took an experiment's goal action, by arm.
//
// An action such as casting a vote, never how anyone voted. Sent once per visitor and experiment, and only after that visitor's exposure.
//
// Instrument: counter. Unit: {visitor}. Stability: development.
//
// Attributes:
//   - justabill.experiment.id (required)
//   - justabill.experiment.variant (required)
const ExperimentConversionsName = "justabill.experiment.conversions"

// ExperimentConversionsUnit is the UCUM unit of justabill.experiment.conversions.
const ExperimentConversionsUnit = "{visitor}"

// ExperimentConversionsDescription is the description of justabill.experiment.conversions.
const ExperimentConversionsDescription = "Visitors who took an experiment's goal action, by arm."

// ExperimentExposuresName is the metric justabill.experiment.exposures.
//
// Visitors who saw an experiment's page, by arm.
//
// The browser sends one exposure per visitor and experiment to POST /api/experiments, which takes the arm from the visitor's jab_exp cookie (docs/design/580-ab-experiments.md).
//
// Instrument: counter. Unit: {visitor}. Stability: development.
//
// Attributes:
//   - justabill.experiment.id (required)
//   - justabill.experiment.variant (required)
const ExperimentExposuresName = "justabill.experiment.exposures"

// ExperimentExposuresUnit is the UCUM unit of justabill.experiment.exposures.
const ExperimentExposuresUnit = "{visitor}"

// ExperimentExposuresDescription is the description of justabill.experiment.exposures.
const ExperimentExposuresDescription = "Visitors who saw an experiment's page, by arm."

// LawChangeResultsName is the metric justabill.law_change.results.
//
// Law-change explanation requests to Gemini, by outcome.
//
// One request explains every section of law a bill changes (sync-law-changes). Counted apart from justabill.summary.results so that the summary failure alert and dashboard measure bill and diff summaries only; gen_ai.client.token.usage and gen_ai.client.operation.duration count both.
//
// Instrument: counter. Unit: {request}. Stability: development.
//
// Attributes:
//   - gen_ai.request.model (required)
//   - justabill.summary.outcome (required)
const LawChangeResultsName = "justabill.law_change.results"

// LawChangeResultsUnit is the UCUM unit of justabill.law_change.results.
const LawChangeResultsUnit = "{request}"

// LawChangeResultsDescription is the description of justabill.law_change.results.
const LawChangeResultsDescription = "Law-change explanation requests to Gemini, by outcome."

// PipelineItemsName is the metric justabill.pipeline.items.
//
// Items handled by pipeline jobs, by outcome.
//
// Instrument: counter. Unit: {item}. Stability: development.
//
// Attributes:
//   - justabill.item.outcome (required)
//   - justabill.job.name (required)
const PipelineItemsName = "justabill.pipeline.items"

// PipelineItemsUnit is the UCUM unit of justabill.pipeline.items.
const PipelineItemsUnit = "{item}"

// PipelineItemsDescription is the description of justabill.pipeline.items.
const PipelineItemsDescription = "Items handled by pipeline jobs, by outcome."

// PipelineJobDurationName is the metric justabill.pipeline.job.duration.
//
// How long pipeline job runs take.
//
// Instrument: histogram. Unit: s. Stability: development.
//
// Attributes:
//   - justabill.job.name (required)
//   - justabill.job.outcome (required)
const PipelineJobDurationName = "justabill.pipeline.job.duration"

// PipelineJobDurationUnit is the UCUM unit of justabill.pipeline.job.duration.
const PipelineJobDurationUnit = "s"

// PipelineJobDurationDescription is the description of justabill.pipeline.job.duration.
const PipelineJobDurationDescription = "How long pipeline job runs take."

// PipelineJobLastSuccessName is the metric justabill.pipeline.job.last_success.
//
// When a pipeline job last finished successfully, as Unix time in seconds.
//
// Instrument: gauge. Unit: s. Stability: development.
//
// Attributes:
//   - justabill.job.name (required)
const PipelineJobLastSuccessName = "justabill.pipeline.job.last_success"

// PipelineJobLastSuccessUnit is the UCUM unit of justabill.pipeline.job.last_success.
const PipelineJobLastSuccessUnit = "s"

// PipelineJobLastSuccessDescription is the description of justabill.pipeline.job.last_success.
const PipelineJobLastSuccessDescription = "When a pipeline job last finished successfully, as Unix time in seconds."

// SummaryResultsName is the metric justabill.summary.results.
//
// Bill summary requests to Gemini, by outcome.
//
// Instrument: counter. Unit: {summary}. Stability: development.
//
// Attributes:
//   - gen_ai.request.model (required)
//   - justabill.summary.outcome (required)
const SummaryResultsName = "justabill.summary.results"

// SummaryResultsUnit is the UCUM unit of justabill.summary.results.
const SummaryResultsUnit = "{summary}"

// SummaryResultsDescription is the description of justabill.summary.results.
const SummaryResultsDescription = "Bill summary requests to Gemini, by outcome."

// UpstreamQuotaRemainingName is the metric justabill.upstream.quota.remaining.
//
// Requests left in the upstream API's rate-limit window.
//
// Read from the `X-RateLimit-Remaining` response header of Congress.gov and GovInfo.
//
// Instrument: gauge. Unit: {request}. Stability: development.
//
// Attributes:
//   - server.address (required)
const UpstreamQuotaRemainingName = "justabill.upstream.quota.remaining"

// UpstreamQuotaRemainingUnit is the UCUM unit of justabill.upstream.quota.remaining.
const UpstreamQuotaRemainingUnit = "{request}"

// UpstreamQuotaRemainingDescription is the description of justabill.upstream.quota.remaining.
const UpstreamQuotaRemainingDescription = "Requests left in the upstream API's rate-limit window."

// VercelDrainLagName is the metric justabill.vercel.drain.lag.
//
// How long after its timestamp a Vercel log drain line reached vercel-drain.
//
// Instrument: histogram. Unit: s. Stability: development.
//
// Attributes:
//   - justabill.vercel.source (required)
const VercelDrainLagName = "justabill.vercel.drain.lag"

// VercelDrainLagUnit is the UCUM unit of justabill.vercel.drain.lag.
const VercelDrainLagUnit = "s"

// VercelDrainLagDescription is the description of justabill.vercel.drain.lag.
const VercelDrainLagDescription = "How long after its timestamp a Vercel log drain line reached vercel-drain."

// VercelDrainLinesName is the metric justabill.vercel.drain.lines.
//
// Vercel log drain lines vercel-drain received, by shape and outcome.
//
// The census that checks the failure counting rule against production data (design 473).
//
// Instrument: counter. Unit: {line}. Stability: development.
//
// Attributes:
//   - justabill.vercel.line.outcome (required)
//   - justabill.vercel.log.type (required)
//   - justabill.vercel.source (required)
//   - justabill.vercel.status_class (required)
const VercelDrainLinesName = "justabill.vercel.drain.lines"

// VercelDrainLinesUnit is the UCUM unit of justabill.vercel.drain.lines.
const VercelDrainLinesUnit = "{line}"

// VercelDrainLinesDescription is the description of justabill.vercel.drain.lines.
const VercelDrainLinesDescription = "Vercel log drain lines vercel-drain received, by shape and outcome."

// VercelFunctionFailuresName is the metric justabill.vercel.function.failures.
//
// Web function requests that crashed, timed out or failed, counted once each from Vercel's drain lines.
//
// Deduplicated by Vercel's request ID for 15 minutes on each vercel-drain replica, so a request whose lines reach both replicas can count twice. Carries no path, host, request ID or IP. Design docs/design/473-vercel-function-failures.md.
//
// Instrument: counter. Unit: {request}. Stability: development.
//
// Attributes:
//   - http.response.status_code ({"conditionally_required": "When the line carries a valid HTTP status."})
//   - justabill.vercel.failure.kind (required)
const VercelFunctionFailuresName = "justabill.vercel.function.failures"

// VercelFunctionFailuresUnit is the UCUM unit of justabill.vercel.function.failures.
const VercelFunctionFailuresUnit = "{request}"

// VercelFunctionFailuresDescription is the description of justabill.vercel.function.failures.
const VercelFunctionFailuresDescription = "Web function requests that crashed, timed out or failed, counted once each from Vercel's drain lines."

// WebFixtureFallbackName is the metric justabill.web.fixture_fallback.
//
// Pages the web app rendered from example fixtures because the API call failed.
//
// Counted in `api.ts` until #73 removes the fixture fallback in production.
//
// Instrument: counter. Unit: {render}. Stability: development.
//
// Attributes:
//   - http.route (required)
const WebFixtureFallbackName = "justabill.web.fixture_fallback"

// WebFixtureFallbackUnit is the UCUM unit of justabill.web.fixture_fallback.
const WebFixtureFallbackUnit = "{render}"

// WebFixtureFallbackDescription is the description of justabill.web.fixture_fallback.
const WebFixtureFallbackDescription = "Pages the web app rendered from example fixtures because the API call failed."

// PipelineJobFinishedEvent is the event name justabill.pipeline.job.finished.
//
// A pipeline job run finished.
//
// Emitted once per run by the scheduler and backfill, whatever the outcome.
//
// Stability: development.
//
// Attributes:
//   - justabill.job.duration (required)
//   - justabill.job.items.failed (recommended)
//   - justabill.job.items.ok (recommended)
//   - justabill.job.name (required)
//   - justabill.job.outcome (required)
const PipelineJobFinishedEvent = "justabill.pipeline.job.finished"

// VercelAlertEvent is the event name justabill.vercel.alert.
//
// Vercel raised an alert, such as a usage or error anomaly, forwarded by vercel-drain.
//
// Stability: development.
//
// Attributes:
//   - justabill.vercel.alert.type (required)
const VercelAlertEvent = "justabill.vercel.alert"

// VercelDeploymentEvent is the event name justabill.vercel.deployment.
//
// A Vercel deployment changed state, forwarded by vercel-drain.
//
// Stability: development.
//
// Attributes:
//   - justabill.vercel.deployment.state (required)
const VercelDeploymentEvent = "justabill.vercel.deployment"
