"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";
import type { BillTextDiff, DiffDetailResponse, SectionDiff, DiffStats } from "@/lib/types";
import { getDiff } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { htmlToText } from "@/lib/utils";

interface DiffCardProps {
  diff: BillTextDiff;
  billId: string;
  isExpanded: boolean;
  onToggle: () => void;
  /** The heading on the toggle; "Version Comparison" by default. */
  title?: string;
  /** A one-line toggle with less padding, for diffs listed between text versions (#665). */
  compact?: boolean;
}

export function DiffCard({ diff, billId, isExpanded, onToggle, title, compact }: DiffCardProps) {
  // The bill page carries only the diff's metadata; its section changes and
  // AI summary load from /diffs/{did} the first time it's expanded.
  const [detail, setDetail] = useState<DiffDetailResponse | null>(null);
  const [failed, setFailed] = useState(false);
  const hasFetchedRef = useRef(false);
  const stats = diff.diff_stats;

  useEffect(() => {
    if (!isExpanded || hasFetchedRef.current) return;
    hasFetchedRef.current = true;
    let cancelled = false;
    let settled = false;
    getDiff(billId, diff.id)
      .then((response) => {
        if (!cancelled) setDetail(response);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      })
      .finally(() => {
        settled = true;
      });
    return () => {
      cancelled = true;
      // A fetch cut short by collapsing runs again on the next expand.
      if (!settled) hasFetchedRef.current = false;
    };
  }, [isExpanded, billId, diff.id]);

  const isLoading = isExpanded && detail === null && !failed;
  const summary = detail?.summary ?? null;
  const sections = detail?.diff.diff_content ?? [];

  return (
    <div className="rounded-lg border border-border">
      {/* Header */}
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={isExpanded}
        className={`flex w-full items-center justify-between gap-4 text-left hover:bg-muted/50 transition-colors ${
          compact ? "min-h-11 px-3 py-2" : "p-4"}`}
      >
        <div className={compact ? "flex min-w-0 flex-wrap items-center gap-x-3 gap-y-0.5" : ""}>
          <p className={compact ? "text-sm text-foreground" : "font-medium text-foreground"}>{title ?? "Version Comparison"}</p>
          {stats && <DiffStatsDisplay stats={stats} compact={compact} />}
        </div>
        <ChevronIcon aria-hidden="true" className={`h-5 w-5 shrink-0 text-muted-foreground transition-transform ${isExpanded ? "rotate-180" : ""}`} />
      </button>

      {/* Expanded content */}
      {isExpanded && (
        <div className={`border-t border-border ${compact ? "p-3" : "p-4"}`}>
          {/* Loading state */}
          {isLoading && (
            <div role="status" aria-label="Loading changes" className="rounded-lg border border-border bg-muted/40 p-4 mb-4">
              <div className="flex items-center gap-2 mb-2">
                <Skeleton className="h-4 w-4" />
                <Skeleton className="h-4 w-24" />
              </div>
              <Skeleton className="h-4 w-full mb-2" />
              <Skeleton className="h-4 w-3/4" />
            </div>
          )}

          {/* AI Summary */}
          {!isLoading && summary && (
            <div className="rounded-lg border border-border bg-muted/40 p-4 mb-4">
              <div className="flex items-center gap-2 mb-2">
                <SparklesIcon className="h-4 w-4 text-muted-foreground" />
                <h4 className="text-sm font-semibold text-foreground">What changed: AI summary</h4>
              </div>
              <p className="mb-2 text-xs text-muted-foreground">
                AI-generated from the two versions&apos; text and not reviewed by a person. It may contain errors.{" "}
                <Link href="/methodology#summaries" className="underline underline-offset-2 hover:text-foreground">
                  How summaries are made
                </Link>
              </p>
              <p className="text-sm text-foreground leading-relaxed">{summary.summary}</p>
              {summary.model_used && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Generated by {summary.model_used}
                </p>
              )}
            </div>
          )}

          {/* Section-by-section changes */}
          {failed ? (
            <p className="text-sm text-destructive">Failed to load the changes.</p>
          ) : isLoading ? null : sections.length > 0 ? (
            <div className="space-y-4">
              {sections.map((section, index) => (
                <SectionDiffDisplay key={`${section.section_id}-${index}`} section={section} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No detailed changes available.</p>
          )}
        </div>
      )}
    </div>
  );
}

function DiffStatsDisplay({ stats, compact }: { stats: DiffStats; compact?: boolean }) {
  const unchanged = stats.sections_added + stats.sections_removed + stats.sections_modified +
    stats.words_added + stats.words_removed === 0;
  const spacing = compact ? "text-xs" : "mt-1 text-sm";
  if (unchanged) return <p className={`${spacing} text-muted-foreground`}>No changes to the text</p>;
  return (
    <div className={`${spacing} flex flex-wrap items-center gap-3`}>
      {stats.sections_added > 0 && (
        <span className="text-vote-yea">+{stats.sections_added} sections</span>
      )}
      {stats.sections_removed > 0 && (
        <span className="text-vote-nay">-{stats.sections_removed} sections</span>
      )}
      {stats.sections_modified > 0 && (
        <span className="text-foreground">{stats.sections_modified} modified</span>
      )}
      <span className="text-muted-foreground">
        {stats.words_added > 0 && `+${stats.words_added.toLocaleString()} words`}
        {stats.words_added > 0 && stats.words_removed > 0 && " / "}
        {stats.words_removed > 0 && `-${stats.words_removed.toLocaleString()} words`}
      </span>
    </div>
  );
}

function SectionDiffDisplay({ section }: { section: SectionDiff }) {
  const typeStyles = {
    added: "border-l-vote-yea bg-vote-yea/5",
    removed: "border-l-vote-nay bg-vote-nay/5",
    modified: "border-l-foreground bg-muted/40",
    unchanged: "border-l-border",
  };

  const typeLabels = {
    added: "Added",
    removed: "Removed",
    modified: "Modified",
    unchanged: "Unchanged",
  };

  const typeBadgeVariants: Record<string, "success" | "destructive" | "secondary"> = {
    added: "success",
    removed: "destructive",
    modified: "secondary",
    unchanged: "secondary",
  };

  // Safely extract plain text from header (may contain HTML entities)
  const cleanHeader = htmlToText(section.header);

  return (
    <div className={`rounded-lg border-l-4 p-4 ${typeStyles[section.type]}`}>
      <div className="flex items-center justify-between gap-2 mb-2">
        <h4 className="font-medium text-foreground text-sm">{cleanHeader || "Section"}</h4>
        <Badge variant={typeBadgeVariants[section.type]}>{typeLabels[section.type]}</Badge>
      </div>

      {section.type === "removed" && section.old_text && (
        <p className="text-sm text-vote-nay line-through">{truncateText(section.old_text, 200)}</p>
      )}

      {section.type === "added" && section.new_text && (
        <p className="text-sm text-vote-yea">{truncateText(section.new_text, 200)}</p>
      )}

      {section.type === "modified" && (
        <div className="space-y-2">
          {section.old_text && (
            <p className="text-sm text-vote-nay line-through">{truncateText(section.old_text, 150)}</p>
          )}
          {section.new_text && (
            <p className="text-sm text-vote-yea">{truncateText(section.new_text, 150)}</p>
          )}
        </div>
      )}
    </div>
  );
}

function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength).trim() + "...";
}

function ChevronIcon({ className, ...props }: { className?: string; "aria-hidden"?: "true" }) {
  return (
    <svg className={className} {...props} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
    </svg>
  );
}

function SparklesIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
    </svg>
  );
}
