import { readFile } from "node:fs/promises";
import { devices, expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { expectAccessible } from "./axe";
import { isCspViolation } from "./csp";
import {
  fillAddress,
  isHelperIframe,
  POPUP_TEST_TIMEOUT,
  seedSession,
  SIGN_IN_TEST_TIMEOUT,
  signInThroughPopupFresh,
  uniqueSubject,
  voteYeaOnHouseBill,
} from "./flows";
import { HOUSE_BILL, SENATE_BILL, STUB_ADDRESS } from "./helpers";

// Sign-in (#137, docs/design/55-social-auth.md "Testing"): the real sign-in page and Firebase JS
// SDK against the Firebase Auth emulator, and the API verifying the emulator's ID tokens. It needs
// the emulator and a web build with accounts on, so it runs under `task e2e:sign-in`
// (E2E_AUTH_EMULATOR_HOST set) and is skipped otherwise. #250 adds it to CI.
//
// Only the first two tests sign in through the emulator's Google popup, which depends on a script
// from apis.google.com (#777); the others start from a session the emulator minted (seedSession) and
// visit /login with it, so the page still reads or creates the account and runs onboarding.

test.skip(!process.env.E2E_AUTH_EMULATOR_HOST, "needs the Auth emulator: task e2e:sign-in");
test.describe.configure({ timeout: SIGN_IN_TEST_TIMEOUT });

/** Finishes the emulator's fake Google popup as a new, auto-generated user. */
async function autoGeneratedUser(popup: Page) {
  // Once earlier tests have made accounts, the emulator lists them first, and it renders that list
  // after load, which can swallow a click on "Add new account". Click until the form shows.
  const autoGenerate = popup.getByRole("button", { name: "Auto-generate user information" });
  await expect(async () => {
    if (!(await autoGenerate.isVisible())) await popup.getByText("Add new account").click({ timeout: 1_000 });
    await expect(autoGenerate).toBeVisible({ timeout: 1_000 });
  }).toPass({ timeout: 15_000 });
  await autoGenerate.click();
  await popup.getByRole("button", { name: /Sign in with Google/ }).click();
}

/** Visits /login?next= as a new account with a seeded session: the page then goes on by itself. */
async function signInNewAccount(page: Page, next: string) {
  await seedSession(page, uniqueSubject());
  await page.goto(`/login?next=${encodeURIComponent(next)}`);
}

// An iPhone in Chromium: Firebase picks what to load from the user agent, and a describe block
// can't switch the project's browser (defaultBrowserType).
const { userAgent, viewport, deviceScaleFactor, isMobile, hasTouch } = devices["iPhone 15"];
const iPhone = { userAgent, viewport, deviceScaleFactor, isMobile, hasTouch };

/** Whether a frame is Firebase's sign-in helper iframe: /__/auth/iframe, or the emulator's. */
const isAuthIframe = (url: string) => /\/auth\/iframe$/.test(new URL(url).pathname);

/** axe on the page as it is, in light and then dark (#83): these pages exist only with accounts on. */
async function expectBothSchemesAccessible(page: Page, what: string) {
  for (const colorScheme of ["light", "dark"] as const) {
    await page.emulateMedia({ colorScheme });
    await expectAccessible(page, `${what} (${colorScheme})`);
  }
  await page.emulateMedia({ colorScheme: null });
}

/**
 * Waits for a fresh window of the API's account-route limit (authRateLimit: 30 requests a minute per
 * IP, a fixed window). Every test here shares one IP, and the tests above use most of a window. It
 * spends what's left with signed-out GET /me calls (401s count too), then waits out Retry-After.
 */
async function startFreshAccountWindow(request: APIRequestContext) {
  const me = `http://localhost:${process.env.E2E_API_PORT ?? "18080"}/api/v1/me`;
  for (let i = 0; i <= 30; i++) {
    const res = await request.get(me);
    if (res.status() === 429) {
      await new Promise((r) => setTimeout(r, Number(res.headers()["retry-after"] ?? "60") * 1_000));
      return;
    }
  }
  throw new Error("GET /me was never rate limited: has authRateLimit changed?");
}

test("signs in with Google, saves a district, stays signed in and signs out", async ({ browser }) => {
  test.setTimeout(POPUP_TEST_TIMEOUT);
  const cspViolations: string[] = [];
  const accountCalls: { method: string; auth: string | undefined }[] = [];
  // Each popup attempt has its own context and page; only the attempt that signs in counts.
  const page = await signInThroughPopupFresh(browser, "/login?next=/settings", autoGeneratedUser, (attempt) => {
    cspViolations.length = 0;
    accountCalls.length = 0;
    attempt.on("console", (msg) => {
      // Every violation but gapi's sampled gen_204 beacon, which connect-src blocks on purpose (#751).
      if (isCspViolation(msg.text())) cspViolations.push(msg.text());
    });
    attempt.on("request", (r) => {
      if (new URL(r.url()).pathname === "/api/v1/me") {
        accountCalls.push({ method: r.method(), auth: r.headers()["authorization"] });
      }
    });
  });
  try {
    await signsUpAndOut(page, accountCalls);
  } finally {
    await page.context().close();
  }
  expect(cspViolations).toEqual([]);
});

/** How long the regression test holds the helper iframe's document, so the popup opens first (#794). */
const HELPER_IFRAME_DELAY_MS = 500;

// #794: the popup sign-in stalled in CI when the popup opened before the emulator's helper iframe
// asked for apis.google.com/js/api.js and the emulator was on another site than the page: that
// request was never sent. The browser now reaches the emulator on the page's site (localhost), where
// that order is harmless. This test forces the order with one attempt: pointed at a cross-site
// emulator (a web build with NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099, and the
// same-site checks bypassed), it fails.
test("signs in through the popup when it opens before the helper iframe asks for Google's script", async ({
  browser,
}) => {
  let popupAt = 0;
  let helperScriptAt = 0;
  const page = await signInThroughPopupFresh(
    browser,
    "/login?next=/settings",
    autoGeneratedUser,
    async (attempt) => {
      attempt.on("popup", () => (popupAt ||= performance.now()));
      attempt.context().on("request", (r) => {
        if (new URL(r.url()).hostname === "apis.google.com" && isHelperIframe(r.frame().url())) {
          helperScriptAt ||= performance.now();
        }
      });
      await attempt.route(
        (url) => isHelperIframe(url.toString()),
        async (route) => {
          await new Promise((resolve) => setTimeout(resolve, HELPER_IFRAME_DELAY_MS));
          await route.continue();
        },
      );
    },
    1,
  );
  try {
    await expect(page).toHaveURL(/\/signup\?next=%2Fsettings$/);
  } finally {
    await page.context().close();
  }
  // The delay did put the popup first, the order that stalled.
  expect(popupAt).toBeGreaterThan(0);
  expect(helperScriptAt).toBeGreaterThan(popupAt);
});

/** The popup test after sign-in: onboarding, settings, a reload and signing out. */
async function signsUpAndOut(page: Page, accountCalls: { method: string; auth: string | undefined }[]) {
  // A first sign-in: GET /me answers no_account, then POST /me creates it. Both carry the token.
  // The new account goes through onboarding (#138) on its way to ?next=.
  await expect(page).toHaveURL(/\/signup\?next=%2Fsettings$/);
  await expect(page.getByText("You haven't set your district yet.")).toBeVisible();
  expect(accountCalls.map((c) => c.method)).toEqual(["GET", "POST"]);
  for (const call of accountCalls) expect(call.auth).toMatch(/^Bearer \S+\.\S+\./);

  // The census stub puts every address in CA-12. The four fields (#741) go out as one line.
  const form = page.getByRole("form", { name: "Home address" });
  await fillAddress(form);
  const lookup = page.waitForRequest((r) => r.method() === "POST" && new URL(r.url()).pathname === "/api/v1/reps");
  await form.getByRole("button", { name: "Save district" }).click();
  expect((await lookup).postDataJSON()).toEqual({ address: STUB_ADDRESS });
  await expect(page.getByText("Your district is saved.")).toBeVisible();
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page).toHaveURL(/\/settings$/);
  await expect(page.getByText(/Your district:/)).toContainText("CA-12");
  await expect(page.getByRole("link", { name: "Settings" })).toBeVisible();

  // The session survives a reload (IndexedDB), and the account is read back, not created again.
  accountCalls.length = 0;
  await page.reload();
  await expect(page.getByText(/Your district:/)).toContainText("CA-12");
  expect(accountCalls.map((c) => c.method)).toEqual(["GET"]);

  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page.getByText("Sign in to see your settings")).toBeVisible();
  await expect(page.getByRole("link", { name: "Sign in" }).first()).toBeVisible();
}

test("a signed-in visitor on /login goes straight to ?next=", async ({ page }) => {
  await signInNewAccount(page, "/bills");
  // Onboarding comes once per account and device; skipping it is fine.
  await expect(page).toHaveURL(/\/signup\?next=%2Fbills$/);
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page).toHaveURL(/\/bills$/);

  await page.goto("/login?next=/vote");
  await expect(page).toHaveURL(/\/vote$/);
});

test("adds this device's votes, votes into the account, downloads the data and deletes the account", async ({
  page,
}) => {
  // Signed out, the vote stays on this device (#72).
  await voteYeaOnHouseBill(page);
  await expect(page.getByText("Kept on this device only. Your vote isn't sent anywhere.")).toBeVisible();

  const votePosts: { url: string; auth: string | undefined }[] = [];
  page.on("request", (r) => {
    if (r.method() === "POST" && /\/api\/v1\/(bills\/[^/]+\/vote|me\/votes:import)$/.test(new URL(r.url()).pathname)) {
      votePosts.push({ url: new URL(r.url()).pathname, auth: r.headers()["authorization"] });
    }
  });

  await signInNewAccount(page, `/bills/${SENATE_BILL.id}`);

  // Onboarding offers the device's vote, and sends nothing until asked.
  await expect(page.getByText("You voted on 1 bill before signing in.", { exact: false })).toBeVisible();
  expect(votePosts).toEqual([]);
  await expectBothSchemesAccessible(page, "onboarding with the offer to add this device's votes");
  await page.getByRole("button", { name: "Add 1 vote to my account" }).click();
  await expect(page.getByText("Added 1 vote to your account.")).toBeVisible();
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page).toHaveURL(new RegExp(`/bills/${SENATE_BILL.id}$`));

  // Signed in, a vote goes to the account with the token, and there's no "this device" note. The
  // button shows the choice while it saves, so wait for the API's answer.
  const cast = page.waitForResponse((r) => r.request().method() === "POST" && r.url().endsWith(`/bills/${SENATE_BILL.id}/vote`));
  await page.getByRole("button", { name: "Nay", exact: true }).click();
  expect((await cast).status()).toBe(200);
  await expect(page.getByRole("button", { name: "Nay", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(votePosts.map((p) => p.url)).toEqual(["/api/v1/me/votes:import", `/api/v1/bills/${SENATE_BILL.id}/vote`]);
  for (const p of votePosts) expect(p.auth).toMatch(/^Bearer /);
  await expect(page.getByText(/Kept on this device/)).toHaveCount(0);

  // The imported vote shows from the account, and the device copy is gone.
  await page.goto(`/bills/${HOUSE_BILL.id}`);
  await expect(page.getByRole("button", { name: "Yea", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(await page.evaluate(() => localStorage.getItem("jab.votes.v1"))).not.toContain(HOUSE_BILL.id);

  // Download my data is exactly what the API keeps.
  await page.goto("/settings");
  const downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download my data" }).click();
  const download = await downloading;
  expect(download.suggestedFilename()).toBe("just-a-bill-account.json");
  const data = JSON.parse(await readFile((await download.path())!, "utf8")) as {
    votes: { bill_id: string; vote: string }[];
  };
  expect(data.votes.map((v) => [v.bill_id, v.vote]).sort()).toEqual([
    [HOUSE_BILL.id, "yea"],
    [SENATE_BILL.id, "nay"],
  ]);

  // Deleting it signs out; the sign-in just now is recent enough for the API.
  const deleted = page.waitForResponse((r) => r.request().method() === "DELETE" && new URL(r.url()).pathname === "/api/v1/me");
  await page.getByRole("button", { name: "Delete my account" }).click();
  await expectBothSchemesAccessible(page, "settings with the deletion confirmation open");
  await page.getByRole("group").getByRole("button", { name: "Delete my account" }).click();
  expect((await deleted).status()).toBe(204);
  await expect(page.getByText("Sign in to see your settings")).toBeVisible();
});

test("follows a bill, sees it in settings and unfollows it", async ({ page, request }) => {
  test.setTimeout(120_000);
  await startFreshAccountWindow(request);

  // Signed out, a bill page has no Follow button: nothing but votes is kept (#282).
  await page.goto(`/bills/${HOUSE_BILL.id}`);
  await expect(page.getByRole("button", { name: "Yea", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: /^Follow/ })).toHaveCount(0);

  await signInNewAccount(page, `/bills/${HOUSE_BILL.id}`);
  await expect(page).toHaveURL(/\/signup\?/);
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page).toHaveURL(new RegExp(`/bills/${HOUSE_BILL.id}$`));

  const followed = page.waitForResponse((r) => r.request().method() === "POST" && r.url().endsWith(`/me/favorites/${HOUSE_BILL.id}`));
  await page.getByRole("button", { name: "Follow", exact: true }).click();
  expect((await followed).status()).toBe(200);
  await expect(page.getByRole("button", { name: "Following" })).toHaveAttribute("aria-pressed", "true");

  // The state comes from the account: it survives a reload.
  await page.reload();
  await expect(page.getByRole("button", { name: "Following" })).toBeVisible();

  await page.goto("/settings");
  await expect(page.getByRole("link", { name: HOUSE_BILL.label })).toHaveAttribute("href", `/bills/${HOUSE_BILL.id}`);
  await expectBothSchemesAccessible(page, "settings with a followed bill");
  await page.getByRole("button", { name: `Unfollow ${HOUSE_BILL.label}` }).click();
  await expect(page.getByText("You don't follow any bills yet.")).toBeVisible();

  await page.goto(`/bills/${HOUSE_BILL.id}`);
  await expect(page.getByRole("button", { name: "Follow", exact: true })).toHaveAttribute("aria-pressed", "false");
});

// The Privacy page: a visitor who doesn't sign in loads no third-party scripts. Firebase Auth's
// initialization loads Google's sign-in helper (gapi) on phones and Safari, so the store loads
// Firebase only once someone presses sign-in or has signed in on this device (#757).
test.describe("on an iPhone", () => {
  test.use(iPhone);

  test("a visitor who never signed in loads nothing from apis.google.com and no auth iframe", async ({ page }) => {
    const google: string[] = [];
    await page.route(/^https:\/\/apis\.google\.com\//, (route) => {
      google.push(route.request().url());
      return route.abort();
    });

    await page.goto("/");
    // The Sign in link shows once the auth store knows nobody is signed in (it's in the DOM, though
    // hidden on a phone, outside the menu).
    await expect(page.locator('header a[href="/login"]').first()).toBeAttached();
    await page.goto("/login");
    await expect(page.getByRole("button", { name: "Continue with Google" })).toBeEnabled();
    // Without the fix the store reports signed out only after Firebase's initialization, which has
    // already asked for gapi by then; the grace period covers anything a late script would load.
    await page.waitForLoadState("load");
    await page.waitForTimeout(1_000);

    expect(google).toEqual([]);
    expect(page.frames().map((f) => f.url()).filter(isAuthIframe)).toEqual([]);
  });

  test("signs in with a redirect, and Firebase loads on later pages", async ({ page }) => {
    await page.goto("/login?next=/settings");
    await page.getByRole("button", { name: "Continue with Google" }).click();

    // The emulator's Google page, in this tab instead of a popup.
    await page.waitForURL(/\/emulator\/auth\/handler/);
    const autoGenerate = page.getByRole("button", { name: "Auto-generate user information" });
    await expect(async () => {
      if (!(await autoGenerate.isVisible())) await page.getByText("Add new account").click({ timeout: 1_000 });
      await expect(autoGenerate).toBeVisible({ timeout: 1_000 });
    }).toPass({ timeout: 15_000 });
    await autoGenerate.click();
    await page.getByRole("button", { name: /Sign in with Google/ }).click();

    // Back on /login, the store loads Firebase to finish the sign-in, then onboarding comes.
    await expect(page).toHaveURL(/\/signup\?next=%2Fsettings$/, { timeout: 30_000 });
    await page.getByRole("button", { name: "Continue" }).click();
    await expect(page).toHaveURL(/\/settings$/);

    // A new page load follows the session, because someone signed in here.
    await page.goto("/");
    await expect(page.locator('header a[href="/settings"]').first()).toBeAttached();
  });
});
