-- Code generated by scripts/db-schema.sh from db/migrations; DO NOT EDIT.
--
-- The schema that every file in db/migrations produces, as Spanner reports it (wrench load).
-- Tests and local dev create databases from it in one step. To change the schema, add a
-- migration (task db:new NAME=<slug>) and run task db:schema. The comments explaining the
-- tables are in the migration files, starting with 000001_baseline.sql.

CREATE TABLE SchemaMigrations (
  Version INT64 NOT NULL,
  Dirty BOOL NOT NULL,
) PRIMARY KEY(Version);

CREATE TABLE congresses (
  number INT64 NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  is_current BOOL NOT NULL DEFAULT (false),
) PRIMARY KEY(number);

CREATE TABLE members (
  bioguide_id STRING(36) NOT NULL,
  first_name STRING(MAX) NOT NULL,
  last_name STRING(MAX) NOT NULL,
  birth_year INT64,
  photo_url STRING(MAX),
  official_url STRING(MAX),
  lis_id STRING(36),
) PRIMARY KEY(bioguide_id);

CREATE UNIQUE NULL_FILTERED INDEX idx_members_lis_id ON members(lis_id);

CREATE TABLE member_terms (
  member_id STRING(36) NOT NULL,
  congress INT64 NOT NULL,
  chamber STRING(MAX) NOT NULL,
  state STRING(2) NOT NULL,
  district INT64,
  party STRING(1) NOT NULL,
  start_date DATE,
  end_date DATE,
  CONSTRAINT fk_member_terms_member FOREIGN KEY(member_id) REFERENCES members(bioguide_id),
  CONSTRAINT fk_member_terms_congress FOREIGN KEY(congress) REFERENCES congresses(number),
) PRIMARY KEY(member_id, congress, chamber);

CREATE INDEX idx_member_terms_congress_chamber ON member_terms(congress, chamber);

CREATE INDEX idx_member_terms_district ON member_terms(state, district, congress, chamber);

CREATE TABLE bills (
  bill_id STRING(MAX) NOT NULL,
  congress INT64 NOT NULL,
  bill_type STRING(MAX) NOT NULL,
  number INT64 NOT NULL,
  title STRING(MAX) NOT NULL,
  introduced_date DATE,
  origin_chamber STRING(MAX),
  latest_action JSON,
  current_status STRING(MAX),
  status_date DATE,
  policy_area STRING(MAX),
  sponsors JSON,
  cosponsors JSON,
  committees JSON,
  subjects JSON,
  related_bills JSON,
  policy_area_id STRING(MAX) AS (TRIM(REGEXP_REPLACE(LOWER(policy_area), r'[^a-z0-9]+', '-'), '-')) STORED,
  updated_at TIMESTAMP,
  synced_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
  title_tokens TOKENLIST AS (TOKENIZE_FULLTEXT(title)) HIDDEN,
  gao_checked_at TIMESTAMP,
  laws JSON,
  latest_action_date STRING(MAX) AS (JSON_VALUE(latest_action, '$.actionDate')) STORED,
  CONSTRAINT fk_bills_congress FOREIGN KEY(congress) REFERENCES congresses(number),
) PRIMARY KEY(bill_id);

CREATE INDEX idx_bills_congress ON bills(congress);

CREATE UNIQUE INDEX idx_bills_congress_type_number ON bills(congress, bill_type, number);

CREATE INDEX idx_bills_list_introduced ON bills(congress, introduced_date DESC, bill_id) STORING (bill_type, current_status, origin_chamber, policy_area_id);

CREATE INDEX idx_bills_list_latest_action ON bills(congress, latest_action_date DESC, bill_id) STORING (bill_type, current_status, origin_chamber, policy_area_id);

CREATE INDEX idx_bills_list_status ON bills(congress, current_status, latest_action_date DESC, bill_id) STORING (bill_type, origin_chamber, policy_area_id, updated_at);

CREATE INDEX idx_bills_policy_area ON bills(policy_area_id);

CREATE INDEX idx_bills_status ON bills(current_status);

CREATE SEARCH INDEX idx_bills_title_search ON bills(title_tokens);

CREATE TABLE committees (
  committee_id STRING(MAX) NOT NULL,
  name STRING(MAX) NOT NULL,
  chamber STRING(MAX),
  committee_type STRING(MAX),
  synced_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(committee_id);

CREATE TABLE subjects (
  subject_id STRING(MAX) NOT NULL,
  name STRING(MAX) NOT NULL,
) PRIMARY KEY(subject_id);

CREATE TABLE policy_areas (
  policy_area_id STRING(MAX) NOT NULL,
  name STRING(MAX) NOT NULL,
) PRIMARY KEY(policy_area_id);

CREATE TABLE bill_sponsorships (
  bill_id STRING(MAX) NOT NULL,
  member_id STRING(36) NOT NULL,
  role STRING(MAX) NOT NULL,
  sponsored_date DATE,
  is_original BOOL,
  CONSTRAINT fk_bill_sponsorships_member FOREIGN KEY(member_id) REFERENCES members(bioguide_id) NOT ENFORCED,
) PRIMARY KEY(bill_id, member_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_bill_sponsorships_member ON bill_sponsorships(member_id, role);

CREATE TABLE bill_committees (
  bill_id STRING(MAX) NOT NULL,
  committee_id STRING(MAX) NOT NULL,
  activity STRING(MAX) NOT NULL,
  activity_date TIMESTAMP,
  CONSTRAINT fk_bill_committees_committee FOREIGN KEY(committee_id) REFERENCES committees(committee_id),
) PRIMARY KEY(bill_id, committee_id, activity),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE TABLE bill_subjects (
  bill_id STRING(MAX) NOT NULL,
  subject_id STRING(MAX) NOT NULL,
  CONSTRAINT fk_bill_subjects_subject FOREIGN KEY(subject_id) REFERENCES subjects(subject_id),
) PRIMARY KEY(bill_id, subject_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_bill_subjects_subject ON bill_subjects(subject_id);

CREATE TABLE bill_relations (
  bill_id STRING(MAX) NOT NULL,
  related_bill_id STRING(MAX) NOT NULL,
  relation_type STRING(MAX) NOT NULL,
  identified_by STRING(MAX),
  CONSTRAINT fk_bill_relations_related FOREIGN KEY(related_bill_id) REFERENCES bills(bill_id) NOT ENFORCED,
) PRIMARY KEY(bill_id, related_bill_id, relation_type),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_bill_relations_related ON bill_relations(related_bill_id);

CREATE TABLE bill_status_history (
  bill_id STRING(MAX) NOT NULL,
  status STRING(MAX) NOT NULL,
  status_date DATE NOT NULL,
  status_rank INT64 NOT NULL,
) PRIMARY KEY(bill_id, status),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_bill_status_history_status ON bill_status_history(status);

CREATE TABLE bill_actions (
  bill_id STRING(MAX) NOT NULL,
  action_id STRING(36) NOT NULL DEFAULT (GENERATE_UUID()),
  action_date DATE NOT NULL,
  action_time STRING(MAX),
  action_text STRING(MAX) NOT NULL,
  action_type STRING(MAX),
  action_code STRING(MAX),
  source_system STRING(MAX),
  committee_code STRING(MAX),
  recorded_vote JSON,
  sort_order INT64 NOT NULL,
) PRIMARY KEY(bill_id, action_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_bill_actions_dedup ON bill_actions(bill_id, action_text, sort_order);

CREATE TABLE bill_summaries (
  bill_id STRING(MAX) NOT NULL,
  short_summary STRING(MAX),
  long_summary STRING(MAX),
  why_it_matters STRING(MAX),
  model_used STRING(MAX),
  generated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
  summary_tokens TOKENLIST AS (TOKENIZE_FULLTEXT(COALESCE(short_summary, '') || ' ' || COALESCE(long_summary, ''))) HIDDEN,
  source_version_id STRING(36),
  source_version_code STRING(MAX),
  source_content_hash STRING(MAX),
  prompt_version STRING(MAX),
  model_version STRING(MAX),
  input_truncated BOOL,
  input_tokens INT64,
  output_tokens INT64,
  thinking_tokens INT64,
  source_crs_hash STRING(64),
  source_rule_hash STRING(64),
) PRIMARY KEY(bill_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE SEARCH INDEX idx_bill_summaries_search ON bill_summaries(summary_tokens);

CREATE TABLE bill_text_versions (
  bill_id STRING(MAX) NOT NULL,
  version_id STRING(36) NOT NULL DEFAULT (GENERATE_UUID()),
  version_type STRING(MAX) NOT NULL,
  version_code STRING(MAX) NOT NULL,
  date DATE,
  formats JSON,
  sort_order INT64 NOT NULL,
  synced_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(bill_id, version_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_btv_bill_version_code ON bill_text_versions(bill_id, version_code);

CREATE INDEX idx_btv_id ON bill_text_versions(version_id);

CREATE TABLE bill_texts (
  text_id STRING(36) NOT NULL DEFAULT (GENERATE_UUID()),
  version_id STRING(36) NOT NULL,
  format STRING(MAX) NOT NULL,
  content STRING(MAX) NOT NULL,
  content_hash STRING(MAX) NOT NULL,
  sections JSON,
  fetched_at TIMESTAMP,
  content_gz BYTES(MAX),
) PRIMARY KEY(text_id);

CREATE UNIQUE INDEX idx_bill_texts_version ON bill_texts(version_id) STORING (content_hash, fetched_at);

CREATE TABLE bill_text_diffs (
  bill_id STRING(MAX) NOT NULL,
  diff_id STRING(36) NOT NULL DEFAULT (GENERATE_UUID()),
  from_version_id STRING(36) NOT NULL,
  to_version_id STRING(36) NOT NULL,
  diff_stats JSON,
  diff_content JSON NOT NULL,
  generated_at TIMESTAMP,
  is_empty BOOL NOT NULL DEFAULT (false),
) PRIMARY KEY(bill_id, diff_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_btd_versions ON bill_text_diffs(from_version_id, to_version_id);

CREATE TABLE bill_text_diff_summaries (
  diff_id STRING(36) NOT NULL,
  summary STRING(MAX) NOT NULL,
  model_used STRING(MAX),
  generated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
  prompt_version STRING(MAX),
  model_version STRING(MAX),
  input_tokens INT64,
  output_tokens INT64,
) PRIMARY KEY(diff_id);

CREATE TABLE amendments (
  bill_id STRING(MAX) NOT NULL,
  amendment_id STRING(MAX) NOT NULL,
  congress INT64 NOT NULL,
  amendment_type STRING(MAX) NOT NULL,
  amendment_number INT64 NOT NULL,
  description STRING(MAX),
  purpose STRING(MAX),
  sponsor_id STRING(36),
  latest_action JSON,
  submitted_date DATE,
  chamber STRING(MAX) NOT NULL,
  synced_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(bill_id, amendment_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE TABLE congressional_votes (
  vote_id STRING(MAX) NOT NULL,
  bill_id STRING(MAX),
  congress INT64 NOT NULL,
  chamber STRING(MAX) NOT NULL,
  session INT64,
  roll_number INT64,
  vote_date TIMESTAMP NOT NULL,
  question STRING(MAX),
  result STRING(MAX),
  yeas INT64,
  nays INT64,
  present INT64,
  not_voting INT64,
  CONSTRAINT fk_cv_congress FOREIGN KEY(congress) REFERENCES congresses(number),
) PRIMARY KEY(vote_id);

CREATE INDEX idx_cv_bill ON congressional_votes(bill_id);

CREATE INDEX idx_cv_congress ON congressional_votes(congress);

CREATE TABLE member_votes (
  vote_id STRING(MAX) NOT NULL,
  member_id STRING(36) NOT NULL,
  vote STRING(MAX) NOT NULL,
) PRIMARY KEY(vote_id, member_id),
  INTERLEAVE IN PARENT congressional_votes ON DELETE CASCADE;

CREATE INDEX idx_member_votes_member ON member_votes(member_id) STORING (vote);

CREATE TABLE users (
  user_id STRING(36) NOT NULL,
  auth_uid STRING(128) NOT NULL,
  state STRING(2),
  district INT64,
  created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
  sign_in_provider STRING(32),
  district_changed_at TIMESTAMP,
  agg_excluded_at TIMESTAMP,
) PRIMARY KEY(user_id);

CREATE UNIQUE INDEX idx_users_auth_uid ON users(auth_uid);

CREATE TABLE user_votes (
  user_id STRING(36) NOT NULL,
  bill_id STRING(MAX) NOT NULL,
  vote STRING(MAX) NOT NULL,
  voted_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
  app_check_ok BOOL,
  recorded_at TIMESTAMP,
) PRIMARY KEY(user_id, bill_id),
  INTERLEAVE IN PARENT users ON DELETE CASCADE;

CREATE TABLE user_favorites (
  user_id STRING(36) NOT NULL,
  bill_id STRING(MAX) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(user_id, bill_id),
  INTERLEAVE IN PARENT users ON DELETE CASCADE;

CREATE TABLE gao_reports (
  report_id STRING(MAX) NOT NULL,
  title STRING(MAX) NOT NULL,
  report_number STRING(MAX),
  report_type STRING(MAX),
  published_date DATE,
  summary STRING(MAX),
  pdf_url STRING(MAX),
  html_url STRING(MAX),
  synced_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(report_id);

CREATE TABLE bill_gao_reports (
  bill_id STRING(MAX) NOT NULL,
  report_id STRING(MAX) NOT NULL,
  linked_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
) PRIMARY KEY(bill_id, report_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE TABLE sync_state (
  step STRING(MAX) NOT NULL,
  congress INT64 NOT NULL,
  last_synced_at TIMESTAMP,
  last_offset STRING(MAX),
  items_synced INT64 NOT NULL DEFAULT (0),
  error_count INT64 NOT NULL DEFAULT (0),
  last_error STRING(MAX),
  last_attempt_at TIMESTAMP,
  last_error_at TIMESTAMP,
  consecutive_failures INT64 NOT NULL DEFAULT (0),
) PRIMARY KEY(step, congress);

CREATE TABLE vote_aggregates (
  bill_id STRING(MAX) NOT NULL,
  scope STRING(16) NOT NULL,
  scope_key STRING(8) NOT NULL,
  status STRING(16) NOT NULL,
  yea_pct INT64,
  nay_pct INT64,
  voters_floor INT64,
  published_at TIMESTAMP,
  basis_yea INT64,
  basis_nay INT64,
  hold_reason STRING(32),
  computed_at TIMESTAMP NOT NULL,
) PRIMARY KEY(bill_id, scope, scope_key),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE TABLE rep_alignment (
  member_id STRING(36) NOT NULL,
  congress INT64 NOT NULL,
  scope_key STRING(8) NOT NULL,
  bills_compared INT64 NOT NULL,
  bills_agreed INT64 NOT NULL,
  computed_at TIMESTAMP NOT NULL,
) PRIMARY KEY(member_id, congress, scope_key);

CREATE TABLE sync_retry (
  step STRING(64) NOT NULL,
  congress INT64 NOT NULL,
  item_id STRING(MAX) NOT NULL,
  attempts INT64 NOT NULL,
  first_failed_at TIMESTAMP NOT NULL,
  last_failed_at TIMESTAMP NOT NULL,
  next_attempt_at TIMESTAMP,
  last_error STRING(MAX),
) PRIMARY KEY(step, congress, item_id);

CREATE TABLE pipeline_leases (
  name STRING(MAX) NOT NULL,
  holder STRING(MAX) NOT NULL,
  acquired_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
) PRIMARY KEY(name);

CREATE TABLE usc_release_points (
  release_point STRING(64) NOT NULL,
  published_date DATE,
  source_url STRING(MAX) NOT NULL,
  loaded_at TIMESTAMP,
  section_count INT64,
) PRIMARY KEY(release_point);

CREATE TABLE usc_sections (
  section_id STRING(200) NOT NULL,
  title_number INT64 NOT NULL,
  section_number STRING(64) NOT NULL,
  heading STRING(MAX),
  text STRING(MAX) NOT NULL,
  status STRING(32) NOT NULL,
  positive_law BOOL NOT NULL,
  release_point STRING(64) NOT NULL,
  content_hash STRING(64) NOT NULL,
  updated_at TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
  text_tokens TOKENLIST AS (TOKENIZE_FULLTEXT(COALESCE(heading, '') || ' ' || text)) HIDDEN,
) PRIMARY KEY(section_id);

CREATE SEARCH INDEX idx_usc_sections_search ON usc_sections(text_tokens);

CREATE TABLE bill_law_refs (
  bill_id STRING(MAX) NOT NULL,
  version_id STRING(36) NOT NULL,
  section_id STRING(200) NOT NULL,
  ref_kind STRING(16) NOT NULL,
  cite_text STRING(MAX),
  subsection_path STRING(200),
  instruction STRING(MAX),
  bill_section_ref STRING(200),
) PRIMARY KEY(bill_id, version_id, section_id, ref_kind),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_bill_law_refs_section ON bill_law_refs(section_id, ref_kind);

CREATE TABLE bill_law_changes (
  bill_id STRING(MAX) NOT NULL,
  section_id STRING(200) NOT NULL,
  change_kind STRING(16) NOT NULL,
  explanation STRING(MAX) NOT NULL,
  source_content_hash STRING(64) NOT NULL,
  release_point STRING(64) NOT NULL,
  model_used STRING(MAX) NOT NULL,
  prompt_version STRING(32) NOT NULL,
  generated_at TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(bill_id, section_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE TABLE summary_attempts (
  bill_id STRING(MAX) NOT NULL,
  content_hash STRING(MAX) NOT NULL,
  prompt_version STRING(MAX) NOT NULL,
  model STRING(MAX) NOT NULL,
  outcome STRING(MAX) NOT NULL,
  reason STRING(MAX),
  attempts INT64 NOT NULL,
  attempted_at TIMESTAMP NOT NULL,
  next_attempt_at TIMESTAMP,
  request_type STRING(MAX),
  batch_id STRING(36),
) PRIMARY KEY(bill_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_summary_attempts_attempted_at ON summary_attempts(attempted_at);

CREATE TABLE bill_crs_summaries (
  bill_id STRING(MAX) NOT NULL,
  version_code STRING(8) NOT NULL,
  action_date DATE NOT NULL,
  action_desc STRING(MAX) NOT NULL,
  chamber STRING(16),
  text_html STRING(MAX) NOT NULL,
  text STRING(MAX) NOT NULL,
  content_hash STRING(64) NOT NULL,
  crs_updated_at TIMESTAMP NOT NULL,
  source_updated_at TIMESTAMP NOT NULL,
  synced_at TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(bill_id, version_code),
  INTERLEAVE IN bills;

CREATE TABLE diff_summary_attempts (
  diff_id STRING(36) NOT NULL,
  prompt_version STRING(MAX) NOT NULL,
  model STRING(MAX) NOT NULL,
  outcome STRING(MAX) NOT NULL,
  reason STRING(MAX),
  attempts INT64 NOT NULL,
  attempted_at TIMESTAMP NOT NULL,
  next_attempt_at TIMESTAMP,
) PRIMARY KEY(diff_id);

CREATE INDEX idx_diff_summary_attempts_attempted_at ON diff_summary_attempts(attempted_at);

CREATE TABLE summary_batches (
  batch_id STRING(36) NOT NULL,
  congress INT64 NOT NULL,
  model STRING(MAX) NOT NULL,
  prompt_version STRING(MAX) NOT NULL,
  job_name STRING(MAX),
  state STRING(MAX) NOT NULL,
  bill_count INT64 NOT NULL,
  input_uri STRING(MAX) NOT NULL,
  output_uri STRING(MAX),
  ok_count INT64,
  failed_count INT64,
  created_at TIMESTAMP NOT NULL,
  finished_at TIMESTAMP,
  imported_at TIMESTAMP,
) PRIMARY KEY(batch_id);

CREATE TABLE law_change_attempts (
  bill_id STRING(MAX) NOT NULL,
  content_hash STRING(MAX) NOT NULL,
  prompt_version STRING(MAX) NOT NULL,
  model STRING(MAX) NOT NULL,
  outcome STRING(MAX) NOT NULL,
  reason STRING(MAX),
  attempts INT64 NOT NULL,
  attempted_at TIMESTAMP NOT NULL,
  next_attempt_at TIMESTAMP,
) PRIMARY KEY(bill_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE INDEX idx_law_change_attempts_attempted_at ON law_change_attempts(attempted_at);

CREATE TABLE federal_register_documents (
  document_number STRING(32) NOT NULL,
  citation STRING(32) NOT NULL,
  volume INT64 NOT NULL,
  start_page INT64 NOT NULL,
  end_page INT64 NOT NULL,
  doc_type STRING(32) NOT NULL,
  action STRING(MAX),
  title STRING(MAX) NOT NULL,
  agencies JSON NOT NULL,
  publication_date DATE NOT NULL,
  effective_on DATE,
  abstract STRING(MAX),
  html_url STRING(MAX) NOT NULL,
  pdf_url STRING(MAX),
  docket_id STRING(MAX),
  regulation_id_numbers JSON,
  content_hash STRING(64) NOT NULL,
  fetched_at TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(document_number);

CREATE TABLE bill_cra_rules (
  bill_id STRING(MAX) NOT NULL,
  rule_title STRING(MAX) NOT NULL,
  rule_agency STRING(MAX) NOT NULL,
  cited STRING(MAX),
  gao_opinion BOOL NOT NULL,
  status STRING(16) NOT NULL,
  method STRING(16),
  reason STRING(32),
  document_number STRING(32),
  withdrawn_document_number STRING(32),
  source_text_hash STRING(64),
  matcher_version STRING(16) NOT NULL,
  context_hash STRING(64) NOT NULL,
  checked_at TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(bill_id),
  INTERLEAVE IN PARENT bills ON DELETE CASCADE;

CREATE PROPERTY GRAPH civic_graph
NODE TABLES(
  bills KEY(bill_id) LABEL Bill PROPERTIES(
bill_id,
bill_type,
congress,
current_status,
introduced_date,
number,
origin_chamber,
policy_area_id,
status_date,
title),
members KEY(bioguide_id) LABEL Member PROPERTIES(
bioguide_id,
first_name,
last_name),
congresses KEY(number) LABEL Congress PROPERTIES(
end_date,
is_current,
number,
start_date),
committees KEY(committee_id) LABEL Committee PROPERTIES(
chamber,
committee_id,
committee_type,
name),
subjects KEY(subject_id) LABEL Subject PROPERTIES(
name,
subject_id),
policy_areas KEY(policy_area_id) LABEL PolicyArea PROPERTIES(
name,
policy_area_id),
congressional_votes KEY(vote_id) LABEL RollCall PROPERTIES(
chamber,
congress,
nays,
not_voting,
present,
question,
result,
roll_number,
session,
vote_date,
vote_id,
yeas),
amendments KEY(bill_id, amendment_id) LABEL Amendment PROPERTIES(
amendment_id,
amendment_number,
amendment_type,
chamber,
congress,
description,
purpose,
submitted_date),
gao_reports KEY(report_id) LABEL GaoReport PROPERTIES(
published_date,
report_id,
report_number,
report_type,
title),
usc_sections KEY(section_id) LABEL LawSection PROPERTIES(
heading,
positive_law,
section_id,
section_number,
status,
title_number)
)
EDGE TABLES(
  bill_sponsorships KEY(bill_id, member_id) SOURCE KEY(member_id) REFERENCES members(bioguide_id) DESTINATION KEY(bill_id) REFERENCES bills(bill_id) LABEL SPONSORED PROPERTIES(
is_original,
role,
sponsored_date),
member_votes AS cast_votes KEY(vote_id, member_id) SOURCE KEY(member_id) REFERENCES members(bioguide_id) DESTINATION KEY(vote_id) REFERENCES congressional_votes(vote_id) LABEL CAST_VOTE PROPERTIES(
vote),
congressional_votes AS roll_call_on KEY(vote_id) SOURCE KEY(vote_id) REFERENCES congressional_votes(vote_id) DESTINATION KEY(bill_id) REFERENCES bills(bill_id) LABEL ON_BILL NO PROPERTIES,
bill_relations KEY(bill_id, related_bill_id, relation_type) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(related_bill_id) REFERENCES bills(bill_id) LABEL RELATED_TO PROPERTIES(
identified_by,
relation_type),
bill_committees KEY(bill_id, committee_id, activity) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(committee_id) REFERENCES committees(committee_id) LABEL REFERRED_TO PROPERTIES(
activity,
activity_date),
bill_subjects KEY(bill_id, subject_id) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(subject_id) REFERENCES subjects(subject_id) LABEL ABOUT NO PROPERTIES,
bills AS in_policy_area KEY(bill_id) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(policy_area_id) REFERENCES policy_areas(policy_area_id) LABEL IN_POLICY_AREA NO PROPERTIES,
bills AS introduced_in KEY(bill_id) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(congress) REFERENCES congresses(number) LABEL INTRODUCED_IN NO PROPERTIES,
amendments AS amends KEY(bill_id, amendment_id) SOURCE KEY(bill_id, amendment_id) REFERENCES amendments(bill_id, amendment_id) DESTINATION KEY(bill_id) REFERENCES bills(bill_id) LABEL AMENDS NO PROPERTIES,
amendments AS sponsored_amendment KEY(bill_id, amendment_id) SOURCE KEY(sponsor_id) REFERENCES members(bioguide_id) DESTINATION KEY(bill_id, amendment_id) REFERENCES amendments(bill_id, amendment_id) LABEL SPONSORED_AMENDMENT NO PROPERTIES,
member_terms AS served_in KEY(member_id, congress, chamber) SOURCE KEY(member_id) REFERENCES members(bioguide_id) DESTINATION KEY(congress) REFERENCES congresses(number) LABEL SERVED_IN PROPERTIES(
chamber,
district,
end_date,
party,
start_date,
state),
bill_gao_reports AS cites KEY(bill_id, report_id) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(report_id) REFERENCES gao_reports(report_id) LABEL CITES PROPERTIES(
linked_at),
bill_law_refs AS changes_law KEY(bill_id, version_id, section_id, ref_kind) SOURCE KEY(bill_id) REFERENCES bills(bill_id) DESTINATION KEY(section_id) REFERENCES usc_sections(section_id) LABEL CHANGES_LAW PROPERTIES(
ref_kind,
subsection_path,
version_id)
);
