#!/usr/bin/env bash
# Regenerates db/schema.sql from db/migrations, or checks that it is current (--check).
#
# Applies every migration to a throwaway database on the Spanner emulator with wrench, loads
# the DDL Spanner reports, adds a generated-code header and writes (or diffs) db/schema.sql.
# The throwaway database is dropped on exit. Used by `task db:schema`, `task db:schema:check`
# and CI. It only ever runs against the emulator.
#
# Environment: SPANNER_EMULATOR_HOST (required), SPANNER_PROJECT (default justabill-local),
# SPANNER_INSTANCE (default test-instance; it must exist), WRENCH (the wrench command).
set -euo pipefail

usage="usage: $0 [--check]"
mode="write"
case "${1:-}" in
  "") ;;
  --check) mode=check ;;
  *) echo "$usage" >&2; exit 2 ;;
esac

if [[ -z "${SPANNER_EMULATOR_HOST:-}" ]]; then
  echo "db-schema: SPANNER_EMULATOR_HOST is not set; this script only runs against the emulator" >&2
  exit 2
fi

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
schema="$root/db/schema.sql"
read -r -a wrench <<<"${WRENCH:-go run github.com/cloudspannerecosystem/wrench@v1.13.5}"
database="schema_$(od -An -N4 -tx1 /dev/urandom | tr -d ' \n')"
target=(
  --project "${SPANNER_PROJECT:-justabill-local}"
  --instance "${SPANNER_INSTANCE:-test-instance}"
  --database "$database"
)

# wrench reads <directory>/schema.sql and <directory>/migrations. The work directory pairs an
# empty schema (so the database starts empty) with the repo's migrations.
work=$(mktemp -d)
created=false
cleanup() {
  if $created; then
    "${wrench[@]}" drop "${target[@]}" --directory "$work" >/dev/null 2>&1 \
      || echo "db-schema: could not drop throwaway database $database" >&2
  fi
  rm -rf "$work"
}
trap cleanup EXIT
: >"$work/schema.sql"
ln -s "$root/db/migrations" "$work/migrations"

if ! "${wrench[@]}" create "${target[@]}" --directory "$work"; then
  echo "db-schema: could not create a database; is the emulator up with instance" \
    "${SPANNER_INSTANCE:-test-instance}? (task migrate creates it)" >&2
  exit 1
fi
created=true
"${wrench[@]}" migrate up "${target[@]}" --directory "$work" >/dev/null
"${wrench[@]}" load "${target[@]}" --directory "$work" --schema_file loaded.sql

{
  cat <<'EOF'
-- Code generated by scripts/db-schema.sh from db/migrations; DO NOT EDIT.
--
-- The schema that every file in db/migrations produces, as Spanner reports it (wrench load).
-- Tests and local dev create databases from it in one step. To change the schema, add a
-- migration (task db:new NAME=<slug>) and run task db:schema. The comments explaining the
-- tables are in the migration files, starting with 000001_baseline.sql.

EOF
  # The emulator's DDL dump spells out every graph element's property list but drops
  # `NO PROPERTIES`, and a bare label means all columns. Put the clause back on graph elements
  # whose label has no property list, so a database created from the snapshot matches one
  # built from the migrations (a round trip through the snapshot is then byte-identical).
  sed -E '/ KEY\(/ s/( LABEL [A-Za-z_][A-Za-z0-9_]*)(,?)$/\1 NO PROPERTIES\2/' "$work/loaded.sql"
} >"$work/generated.sql"

if [[ $mode == check ]]; then
  if ! cmp -s "$work/generated.sql" "$schema"; then
    diff -u "$schema" "$work/generated.sql" | head -n 60 >&2 || true
    echo "db-schema: db/schema.sql doesn't match db/migrations; run \`task db:schema\`" >&2
    exit 1
  fi
  echo "db/schema.sql matches db/migrations"
else
  cp "$work/generated.sql" "$schema"
  echo "wrote db/schema.sql"
fi
